### PR TITLE
Dismiss scrollbar in alternate screen

### PR DESCRIPTION
**Pull request by mgrant0**
Check if the window is in the alternate screen and don't draw the scrollbar.  Call layout_fix_panes on alternate screen on and off.

### CODE REVIEW

**Comment by nicm** [comment]
I like this, but there is a bug, note the extra half border:
Screenshot 2024-11-12 at 09 45 37
Also I don't like adding `alt_screen` everywhere when it is only used once. How about adding a macro, for example:
~~~~
#define PANE_ALTERNATE_SCREEN(wp) ((wp)->screen->saved_grid == NULL)
~~~~
Or make it work on the screen instead so `SCREEN_IN_ALTERNATE(s)` or something?

**Comment by mgrant0** [comment]
Needing to check the scrollbars option is negative occurs in only one place.  You know what, I'm going to simplify this and just remove that check and always pass it in.

**Comment by nicm** [comment]
Looks good but yes either remove `alt_screen` and check `s->saved_grid` directly or make it a macro, I don't mind which, but if you make it a macro it might be best to do it separately and change the other places `s->saved_grid` is checked for that purpose as well.

**Comment by mgrant0** [comment]
I made those changes now, thanks.  Looks even cleaner.

Ok I redid the MR against main.  Please let me know if I didn't do that correctly.

**Comment by mgrant0** [comment]
The macro is:

```
#define PANE_ALTERNATE_SCREEN(s) ((s)->saved_grid != NULL)
```
Is that the correct name?  Or `SCREEN_ALTERNET_SCREEN` since it checks the `screen` struct?

**Comment by nicm** [comment]
I would go with `SCREEN_IS_ALTERNATE` or something like that, definitely not PANE since it operates on a screen.

**Comment by nicm** [comment]
Great, applied to OpenBSD now, will be in GitHub later. Thanks!

**Pull request closed without merging**
