### PR TITLE
Added PANE_SYNCRONIZE flag for duplicate input to selected panes

### PR DESCRIPTION
**Pull request by Rashpil93**
Hi. In this request, I made it possible to select panes to sync input. I think it will be useful in some cases. I also added the ability to customize the highlight of the selected pane or panes.

### CODE REVIEW

**Comment by nicm** [comment]
How is this any different from using `select-pane -d` and `-e`?

**Comment by Rashpil93** [comment]
> How is this any different from using `select-pane -d` and `-e`?

PANE_INPUTOFF prohibits input to pane.

PANE_SYNCRONIZE allows you to select specific panes for input synchronization and input synchronization will only work in those PANES that have PANE_SYNCRONIZE. 
In other panes it will also be possible to enter something and it will not be synchronized with other panes.

Also, setting pane-synchronized-border-style allows you to select a border style for PANE_SYNCRONIZE and you can immediately see which panes are synchronized.

It also remains possible to select all PANEs for synchronization via select-window -S.

**Comment by nicm** [comment]
OK. But I think this should be done differently:

- Instead of removing `synchronize-panes` and adding new flags to `select-pane` and `select-window`, we should change `synchronize-panes` to be a pane option so it can be set individually with `set-option -p` (look at, for example, `allow-rename`).

- `pane-synchronized-border-style` is then unnecessary because you can leave the check for `synchronized-panes` in the default `pane-active-border-style`.

- Instead of `select-window -S`, I suggest adding a flag to `set-option` to unset a pane option on all panes in the target window.

Also please note than "synchronize" is always spelt with an "h".

**Comment by nicm** [comment]
Is this finished now? Thanks

**Comment by Rashpil93** [comment]
Hi. Yes

**Comment by nicm** [comment]
OK I have applied this, but I changed `set-option` to add an extra flag (`-U`) to unset pane options instead of making `synchronize-panes` work differently. It is in OpenBSD now and will be in GitHub later on. Thanks!

**Pull request closed without merging**
