### PR TITLE
Create Continuous Delivery GitHub Workflow

### PR DESCRIPTION
**Pull request by j352lin**
Created workflow .github/workflows/tagged-release.yml to trigger a release whenever a commit is pushed to main.
Also updated versioning semantics in configure.ac to follow the SemVer semantics.

### CODE REVIEW

**Comment by krader1961** [comment]
This is a massive pull-request that includes several unrelated changes. For example, the series that begins with "modify test-emacs and update ic.yml" appears to be only tangentially related to the purpose of this P.R. and could be done separately. I hope you coordinated this massive change with the project owner. Because if I was the project owner I would reject this without any meaningful review. If you were on my team at my $dayjob and asked me to review this P.R. I would tell you to break it up into smaller pieces that have a single goal and would  give you a negative review at your next performance appraisal.

Please note that I am not commenting on any specific change in this pull-request. It is possible they all make sense and represent improvements to the project. But there are so many changes, and they are so badly organized, it is impossible to perform a meaningful review. For example, I found a commit that modifies *.github/workflows/clang-linter.yml*. Yet that file does not exist in my copy of the repo for this project. Presumably an earlier commit in this P.R. introduces that file. Those changes should already be squashed into a single commit when you ask for a review.

**Comment by krader1961** [comment]
OMFG! See https://github.com/j352lin. This is the only meaningful Github contribution by this account in the past year and appears to be part of a computer science class project. While many of the specifics of this pull-request may have merit (i.e., should be merged) this effort to improve Tmux gets a failing grade from me. Even the interns I mentored while working at Google would never have asked me to review a pull-request like this one.

**Comment by j352lin** [comment]
> OMFG! See https://github.com/j352lin. This is the only meaningful Github contribution by this account in the past year and appears to be part of a computer science class project. While many of the specifics of this pull-request may have merit (i.e., should be merged) this effort to improve Tmux gets a failing grade from me. Even the interns I mentored while working at Google would never have asked me to review a pull-request like this one.

I'm very sorry, I'll create a separate PR for these changes

**Comment by j352lin** [comment]
> OMFG! See https://github.com/j352lin. This is the only meaningful Github contribution by this account in the past year and appears to be part of a computer science class project. While many of the specifics of this pull-request may have merit (i.e., should be merged) this effort to improve Tmux gets a failing grade from me. Even the interns I mentored while working at Google would never have asked me to review a pull-request like this one.

But I also hope that you do not judge a developer by the amount of contributions they make on their GitHub account. Anyone can start their contribution no matter when their last contribution was or if they have made any contributions at all. Contributions are made with good intent and I hope you could make feedbacks with a more encouraging approach.

**Comment by krader1961** [comment]
> I'm very sorry, I'll create a separate PR for these changes

Stop! Are you a university student working toward a computer science degree doing this to satisfy a class requirement? If that is true you may have a fresh perspective and ability to meaningfully improve Tmux. However, you don't seem to understand how changes to projects are handled in the real world. Which is to say, not your university class room environment.

**Comment by krader1961** [comment]
> But I also hope that you do not judge a developer by the amount of contributions they make on their GitHub account.

I do not judge by the number of contributions someone has made using their Github account. I only looked at your account because this pull-request is so awful with respect to how it is structured and its cohesiveness. Again, each individual change may be worth merging. The problem is that this P.R. contains a lot of unrelated changes and the commits that are related should have been squashed into a single commit before you asked for the change to be reviewed. What I see in your pull-request is a university computer science team with a lot of good ideas but no idea how to translate those ideas into a sequence of small changes that can be easily reviewed.

**Comment by j352lin** [comment]
> > I'm very sorry, I'll create a separate PR for these changes
> 
> Stop! Are you a university student working toward a computer science degree doing this to satisfy a class requirement? If that is true you may have a fresh perspective and ability to meaningfully improve Tmux. However, you don't seem to understand how changes to projects are handled in the real world. Which is to say, not your university class room environment.

I have worked in companies before and I agree that this is not how to make pull requests. I had admitted that it was my mistake to create a PR into the tmux repo when I intent to create the PR into my forked repo. If you do not wish for me to create separate PRs for each of the changes, that it fine, I will simply close this PR and not even try to contribute to this project. But I must say, in the real world, PR reviews are not so harsh. This really discourages people from making contributions, school project or not.

**Comment by krader1961** [comment]
> I have worked in companies before and I agree that this is not how to make pull requests.

If you know this pull-request contains too many unrelated changes, and the related changes should have been squashed into a single commit, why did you ask that this pull-request be reviewed?

> But I must say, in the real world, PR reviews are not so harsh.

You are mistaken. I retired as a senior software engineer at Google. My review of this pull-request is less harsh than I would be with someone I work with and know personally.

This pull-request fails fails on several criteria. For example, there are commits that fix previous commits. Those commits should be squashed into a single commit before asking that the change they represent be reviewed. It is not reasonable to ask that a commit you know is incorrect be reviewed when your P.R. in includes a subsequent commit that fixes the earlier commit.

**Comment by j352lin** [comment]
> > I have worked in companies before and I agree that this is not how to make pull requests.
> 
> If you know this pull-request contains too many unrelated changes, and the related changes should have been squashed into a single commit, why did you ask that this pull-request be reviewed?
> 
> > But I must say, in the real world, PR reviews are not so harsh.
> 
> You are mistaken. I retired as a senior software engineer at Google. My review of this pull-request is less harsh than I would be with someone I work with and know personally.
> 
> This pull-request fails fails on several criteria. For example, there are commits that fix previous commits. Those commits should be squashed into a single commit before asking that the change they represent be reviewed. It is not reasonable to ask that a commit you know is incorrect be reviewed when your P.R. in includes a subsequent commit that fixes the earlier commit.

If you take a look at https://github.com/CS489-Tmux-Team8/tmux-team8/pull/12/files, I was intending to create a PR in my forked repo and not a PR in this repo. 
I did not add any reviewers to this PR and I was going to close this PR. I have worked in several companies and I totally agree with you on how this PR fails even my standard. I am thankful that you are pointing out the correct way to create a PR. However, I dislike languages such as "OMFG". But of course, you have the right to comment in any language you like. But I just wanted to say that me and future contributors could be upset and discouraged by such language. I understand that you want to make the tmux project better and I'm very sorry if this PR bothered you.

**Comment by krader1961** [comment]
> If you take a look at https://github.com/CS489-Tmux-Team8/tmux-team8/pull/12/files, I was intending to create a PR in my forked repo and not a PR in this repo.

Are you saying that change is what you wanted to be reviewed? AFAICT that change appears to be a small part of this pull-request. If you accidentally created this pull-request you should have simply said so and closed it. Instead, in response to my initial feedback you wrote this:

> However, I dislike languages such as "OMFG". But of course, you have the right to comment in any language you like. 

I appreciate that English may not be your native language (although you seem to understand English better than many Americans) but you need to grow a thicker skin. You should consider that your first major contribution to a project might be evaluated based on your prior contributions; whether to the project or the open source community as a whole. 

> I  did not add any reviewers to this PR and I was going to close this PR.

The only meaningful reviewer of this P.R. is @nicm (the project owner).  You couldn't add any reviewers to this P.R. that were meaningful. So I don't understand what point you're trying to make other than saying "I did not intend to open this pull-request."d

> I'm very sorry if this PR bothered you.

It only bothered me to the extent that reviewing a large number of commits, many of which are unrelated or correct earlier commits, would bother any code reviewer.

**Comment by j352lin** [comment]
> > If you take a look at https://github.com/CS489-Tmux-Team8/tmux-team8/pull/12/files, I was intending to create a PR in my forked repo and not a PR in this repo.
> 
> Are you saying that change is what you wanted to be reviewed? AFAICT that change appears to be a small part of this pull-request. If you accidentally created this pull-request you should have simply said so and closed it. Instead, in response to my initial feedback you wrote this:
> 
> > However, I dislike languages such as "OMFG". But of course, you have the right to comment in any language you like.
> 
> I appreciate that English may not be your native language (although you seem to understand English better than many Americans) but you need to grow a thicker skin. You should consider that your first major contribution to a project might be evaluated based on your prior contributions; whether to the project or the open source community as a whole.
> 
> > I  did not add any reviewers to this PR and I was going to close this PR.
> 
> The only meaningful reviewer of this P.R. is @nicm (the project owner). You couldn't add any reviewers to this P.R. that were meaningful. So I don't understand what point you're trying to make other than saying "I did not intend to open this pull-request."d
> 
> > I'm very sorry if this PR bothered you.
> 
> It only bothered me to the extent that reviewing a large number of commits, many of which are unrelated or correct earlier commits, would bother any code reviewer.

Again, I apologize for not closing this PR right away. Nothing you said was wrong. And of course, there's still many things for me to learn in this career. Thank you for your feedbacks and advices. And thank you for your contributions to the tmux project.

**Comment by krader1961** [comment]
Also, @j352lin, some of the changes in this pull-request seem valuable to me. Try to separate the changes in this P.R. into much smaller units of change that are independent of each other and focus on a single goal. Pick an improvement to the Tmux project and create a pull-request that includes the minimal number of commits (preferably one) that implements that improvement.

**Comment by j352lin** [comment]
> Also, @j352lin, some of the changes in this pull-request seem valuable to me. Try to separate the changes in this P.R. into much smaller units of change that are independent of each other and focus on a single goal. Pick an improvement to the Tmux project and create a pull-request that includes the minimal number of commits (preferably one) that implements that improvement.

Sure. I am a bit busy this week. I'll try to do that in the next week or so

**Comment by kittydoor** [comment]
@j352lin as a random bystander, thank you so much for you work in trying to improve Tmux.

I'm sorry for the reaction you got to your efforts, I think the tone and personal nature is very unacceptable. However, there is definitely some good advice in there that hopefully is still visible despite the improper communication.

I hope you can let the negativity behind you, clean up the PR a bit, look into `git rebase -i` to properly merge/order the commits in a way someone can actually walk through it, and who knows maybe there will be interest in merging it by the maintainer :)

**Comment by j352lin** [comment]
> @j352lin as a random bystander, thank you so much for you work in trying to improve Tmux.
> 
> I'm sorry for the reaction you got to your efforts, I think the tone and personal nature is very unacceptable. However, there is definitely some good advice in there that hopefully is still visible despite the improper communication.
> 
> I hope you can let the negativity behind you, clean up the PR a bit, look into `git rebase -i` to properly merge/order the commits in a way someone can actually walk through it, and who knows maybe there will be interest in merging it by the maintainer :)

Sounds good. I will look into creating PRs this Monday :)

**Pull request closed without merging**
