### PR TITLE
Add cursor style option

### PR DESCRIPTION
**Pull request by afh**
~~🚧 The changes in this PR can cause tmux spin, i.e. use ~95%, this is a known issue and is being worked on. Until this is resolved this PR should not be merged.~~ ✅ resolved.

~~⚠️ This PRs merge base should be [afh:afh-cursor-color](https://github.com/afh/tmux/tree/afh-cursor-colour); [here are the relevant changes between afh:afh-cursor-color and this PRs branch](https://github.com/afh/tmux/compare/afh-cursor-colour...afh:afh-cursor-style?expand=1)~~ **Update:** [afh:afh-cursor-color](https://github.com/afh/tmux/tree/afh-cursor-colour) has been merged with #2959 and using master as this PRs merge is now correct.

To test:
* Build and run tmux: `./tmux -vv -f/dev/null -Ltest`
* Set the different styles for the cursor: `./tmux set cursor-style $style` where `$style` is on of:`default`, `block-blinking`, `block`, `underline-blinking`, `underline`, `bar-blinking`, `bar`
* Use SM/RM ?12 to set cursor (not) blinking `echo -ne "\033[?12h\a"` / `echo -ne "\033[?12l\a"`
* Use DECSCUSR to change cursor style `echo -en "\033[4 q\a"`

ℹ️ If the changes in this PR are applied the **Options for default cursor style.** item can be removed from the [Contribution — Small things](https://github.com/tmux/tmux/wiki/Contributing#small-things) wiki page

<details id=test_cursor_style><summary><code>test_cursor_style.sh</code></summary>

```
#!/bin/ksh

echo "Cursor should be default. Enter to continue"; read

./tmux set cursor-style bar-blinking
echo "tmux cursor-style set to bar-blinking. Enter to continue"; read

./tmux set -u cursor-style
echo "tmux cursor-style unset. Cursor should be default. Enter to continue"; read

echo -en "\033[4 q\a"
echo "DECSCUSR 4. Cursor should be underline. Enter to continue"; read

echo -ne "\033[?12h\a"
echo "SM 12. Cursor should be blinking. Enter to continue"; read

echo -en "\033[0 q\a"
echo "DECSCUSR 0. Cursor should be default blinking. Enter to continue"; read

./tmux set cursor-style bar
echo "tmux cursor-style set to bar. Cursor should still be blinking due to SM 12. Enter to continue"; read

echo -ne "\033[?12l\a"
echo "RM 12.Cursor should not be blinking. Enter to continue"; read

./tmux set cursor-style block-blinking
echo "tmux cursor-style set to block-blinking. Cursor should not be blinking due to RM 12. Enter to continue"; read

./tmux set -u cursor-style
echo "tmux cursor-style unset. Cursor should be default. Enter to continue"; read
```

</details>

### CODE REVIEW

**Comment by nicm** [comment]
You are still working on this, yes? Nothing new for me to look at?

**Comment by afh** [comment]
Hi @nicm, yes, I was still working on this and just pushed some changes for you to review.
I hope I got the logic right, i.e. the precedence the different ways to change the cursor take.
It took me a bit of time to wrap my head around that.

Looking forward to your feedback :)

**Comment by nicm** [comment]
In `tty_update_cursor`, shouldn't the second `changed` be using `cmode`:
~~~~
        changed  = mode ^ tty->mode;
        if ((changed & CURSOR_MODES) == 0 && cstyle == tty->cstyle)
                return (cmode);

**Comment by nicm** [comment]
Also in `tty_update_mode` you assign `tmode` but don't use it?

I would be inclined to just do something like this which makes it clear what matters about the return value:
~~~
if (tty_update_cursor(tty, mode, s) & MODE_CURSOR_BLINKING)
     mode |= MODE_CURSOR_BLINKING;
else
     mode &= ~MODE_CURSOR_BLINKING;
~~~~

**Comment by nicm** [comment]
Oh you are not finished, you don't use `MODE_CURSOR_BLINKING_CHANGED` yet either.

Maybe we could come up with a shorter flag name...

**Comment by afh** [comment]
Thanks for the thorough review, @nicm :) I've addressed your comments.

<code>MODE_CURSOR_BLINKING_<strike>CHANGED</strike>SET</code> is being used in [`tty.c:700`](https://github.com/tmux/tmux/pull/2960/commits/f3b2004f432e10433824360c1cd643c84a864dfb#diff-2dec3ca953f8622e2bc9fe13a2eb464d057905e6f9313682665328c6b67910e6R700) to use `MODE_CURSOR_BLINKING` from `s->default_mode` when `cstyle == SCREEN_CURSOR_DEFAULT`.

**Comment by reportaman** [comment]
@afh @nicm Why not have cursor color as part of style? That way each pane can have its own color specified using a unified same interface? As of now, one can specify bg, fg, and 16 colors of the terminal color palette for any pane/window/global. Having cursorfg, and cursorbg as part of pane style here would be more natural.

**Comment by nicm** [comment]
I think a separate option is better, the cursor is not really the same as the rest of the style.

**Comment by nicm** [comment]
This looks good and works for me. I have applied this with a few minor changes:

- I prefer `blinking-block` to `block-blinking` for the option values;

- In `tty_update_cursor` we can avoid setting `changed` twice by just checking `tty->mode`for the invisible case;

- There is no need for `tmode` in `tty_update_mode` now;

- I think one `screen_set_cursor_style` function will do.

Thanks!

**Comment by afh** [comment]
The minor changes sound very reasonable, @nicm. Thanks for applying and your help :)

**Pull request closed without merging**
