### PR TITLE
Add options and arguments to display-menu to set menu border lines

### PR DESCRIPTION
**Pull request by afh**
This PR adds border line styling to `display-menu` and is a follow-up PR of #2947.

ℹ️ This PR builds upon the proposed changes from #3649; to only see the relevant changes please see https://github.com/afh/tmux/compare/afh-menu-border-style...afh:tmux:afh-menu-border-lines

To test:
* Build and run tmux `./tmux -vv -f/dev/null -Ltest`
* Set `menu-border-lines` options and display menu (see `test_menu_border_lines.sh` below)
* Use `-b` argument when displaying a menu (see `test_menu_border_lines.sh ` below)

👉 **NOTA BENE:** There are several `TODO:` comments in the code that should to be clarified prior applying the changes.

ℹ️ The `none` style is currently the same as `padded` due to difficulties in removing the border completely, for details see [this comment on #2947](https://github.com/tmux/tmux/pull/2947#issuecomment-1195668262)

ℹ️ The changes in [`tty-acs.c`](https://github.com/tmux/tmux/pull/3650#diff-0061931f0e579d624769a3e92854fbd0db819ee849c4c75d74928eb0114c2abb) fix an issue with the rounded characters which used the heavy ([U+2523](https://unicodeplus.com/U+2523) and [U+252B](https://unicodeplus.com/U+252B)) instead of the light ([U+251C](https://unicodeplus.com/U+251C) and [U+2524](https://unicodeplus.com/U+2524)) variant of the "Box Drawings * Vertical And (Right|Left)" character.  

<details><summary><code> test_menu_border_lines.sh </code></summary>

```sh
#!/bin/ksh

clear
echo "# Expect default tmux border lines menu when unstyled"
echo "% ./tmux set -gwU menu-border-lines"
./tmux set -gwU menu-border-lines
echo "% ./tmux menu -T Default lines '' '' -bar '' '' '' baz '' ''"
./tmux menu -T Default lines '' '' -bar '' '' '' baz '' ''

clear
lines=heavy
echo "# Expect tmux $lines menu border lines when set via tmux options, e.g.:"
echo "% ./tmux set -gw menu-border-lines $lines"
./tmux set -gw menu-border-lines $lines
echo "% ./tmux menu -T $lines lines '' '' -bar '' '' '' baz '' ''"
./tmux menu -T $lines lines '' '' -bar '' '' '' baz '' ''

for lines in double single rounded heavy ; do
clear
echo "# Expect tmux $lines menu border lines when set via tmux arguments overriding previously set options, e.g.:"
echo "% ./tmux menu -T $lines -b $lines lines '' '' -bar '' '' '' baz '' ''"
./tmux menu -T $lines -b $lines lines '' '' -bar '' '' '' baz '' ''
done

clear
lines=padded
echo "# Expect tmux $lines menu border lines when set via tmux arguments overriding previously set options, e.g.:"
echo "% ./tmux menu -T $lines -b $lines -S bg=green lines '' '' -bar '' '' '' baz '' ''"
./tmux menu -T $lines -b $lines -S bg=green lines '' '' -bar '' '' '' baz '' ''

clear
lines=none
echo "# Expect tmux $lines menu border lines when set via tmux arguments overriding previously set options, e.g.:"
echo "% ./tmux menu -T $lines -b $lines -S bg=orange lines '' '' -bar '' '' '' baz '' ''"
./tmux menu -T $lines -b $lines -S bg=orange lines '' '' -bar '' '' '' baz '' ''
```

</details>

| | |
| --- | --- |
| Default | 
| Heavy | 
| Double |  
| Rounded | 
| Padded | 
| None |

### CODE REVIEW

**Comment by nicm** [comment]
Thanks. This mostly looks good. Here are some comments:

- I think all lines in the menu including the separator should be the same as the border, so no need to pass two cells into `screen_write_hline`, only the border is needed.

- In `screen_write_hline`, if `left` or `right` is false it should use `CELL_LEFTRIGHT` - these flags mean a join at that end, if they are false then it should be a normal line end and not a join of either type.

- If you put the new function `screen_write_box_border_set` above `screen_write_hline` in the file, you don't need to add a declaration for it.

- I don't think it is worth breaking compatibility for the minor convenience of using `-S`. Just pick a different flag for `display-menu`.

- For consistency, can you use `lines` for `enum box_lines` arguments not `l` or `box_lines`?

- The `lines = l` bit in `menu_prepare` seems unnecessary?

- What are the `tty-acs.c` changes for? I think you may have said before but I have forgotten...

**Comment by afh** [comment]
Thanks for the helpful comments, @nicm. I'll address in the coming days and will get back to you.

**Comment by afh** [comment]
The changes in [`tty-acs.c`](https://github.com/tmux/tmux/pull/3650#diff-0061931f0e579d624769a3e92854fbd0db819ee849c4c75d74928eb0114c2abb) fix an issue with the rounded characters which used the heavy ([U+2523](https://unicodeplus.com/U+2523) ┣ and [U+252B](https://unicodeplus.com/U+252B) ┫) instead of the light ([U+251C](https://unicodeplus.com/U+251C)├ and [U+2524](https://unicodeplus.com/U+2524) ┤) variant of the "Box Drawings * Vertical And (Right|Left)" character.

<table>
<thead>
<th>Before</th><th>After</th>
</thead>
<tbody><tr><td>

```
╭─rounded─╮
│ lines   │
│ bar     │
┣─────────┫
│ baz     │
╰─────────╯
```

</td><td>

```
╭─rounded─╮
│ lines   │
│ bar     │
├─────────┤
│ baz     │
╰─────────╯
```

</td></tr></tbody></table>

**Comment by nicm** [comment]
OK, I have applied two parts of this with minor changes:

- I applied the `tty-acs.c` bit unchanged.

- I applied the `screen-write.c` with some minor tidying up, mostly to reduce use of `?:` and to make the code (existing and new) fit more neatly until 80 columns. I also removed the changes to the padding around the menu items for the moment.

**Comment by nicm** [comment]
I have applied the rest of this as well, with some minor changes to `tmux.1` (I changed back to `border-lines` for `-b` rather than `type`, it is not as obvious what `type` means here as it is for the options). I also added back the change to colour the padding around the menu items.

Is there anything else remaining here? The two things I can think of are:

- Border lines `none`.

- It would be nice to have an option for the style of the selected item rather than reusing `mode-style`?

**Comment by afh** [comment]
Thanks for accepting the changes, @nicm, very much appreciated! 🙂 
I'll pull the `master` branch into my working copy in the coming days and will inspect the state of things and address your comments and any remaining comments, issues, questions, todos that are related.

**Comment by afh** [comment]
Thank you for applying the rest of the changes and informing me about modifications you made. And thank you very much for reconsidering and using `-C` to pre-select a menu item allowing `-S` for border styling to be consistent across `display-menu` and `display-popup`, greatly appreciated, @nicm! :pray:
Hopefully it will only be minor inconvenience to those using on it. Do let me know if I can help with communicating the change.

I went ahead and worked on the suggestions you mentioned:

* Inline styling now overrides the configured style
* I'd like to propose the addition of the `menu-selected-style` option and the `-H selected-style` argument to the `display-menu` command. Is this in the direction you had mind when saying _"it would be nice to have an option for the style of the selected item rather than reusing `mode-style`"_?
* Minor word-smithing in `tmux.1` to use `border-lines` instead of `type` for the `display-popup` `-p` option.

Apart from the border-line style changes and the items mentioned above nothing is left here, as I'd like to address border-lines `none` in a separate PR. I did make some good progress on it and am happy to share my current work in progress once the changes here are in—my 🧠 can only take so many open PRs at once 😅

**Comment by afh** [comment]
Taking inspiration from the [fzf](https://github.com/junegunn/fzf), which offers block borders using on eigth block characters, e.g.:

```
  ▛▀▀▀▀▀▀▛▀▀▀▀▀▀▀▜
  ▌      ▌       ▐
  ▌      ▌       ▐
  ▙▄▄▄▄▄▄▙▄▄▄▄▄▄▄▟
  ▌      ▌       ▐
  ▙▄▄▄▄▄▄▙▄▄▄▄▄▄▄▟
```

<smaller><sup>*</sup> Note that GitHub's CSS styling seems to break the visual appearance here; is how it looks in my terminal ([alacritty](http://github.com/alacritty/alacritty/pulls)):
image</smaller>

I was wondering whether a `block` border-line would be possible in tmux.
The biggest issue I see is that it seems the `struct utf8_data` used in `tty-acs.c` seems to use the same character for left and right as well as top and bottom borders. Is this observation correct? If yes, would a new border style potentially be worth the effort? What are your thoughts, @nicm?

**Comment by nicm** [comment]
That looks like it is the same character for top and bottom and left and right?

I don't think there is any pressing reason to add a new border style unless you want to use it yourself.

**Comment by afh** [comment]
The looks are deceiving:

* left is U+258C
* right is U+2590
* top is U+2580
* bottom is U+2584

Agreed: no pressing reason, especially with this PR and the border none work pending.

**Comment by nicm** [comment]
I have applied this now with one change to move the style bit in `menu.c` into a common function (`menu_set_style`). Thanks!

If you want to add additional border styles (`none` or the one you mentioned above), then that's great, but if not we can live without them. There are lots of other things to do if you want to do anything else... :-)

**Comment by afh** [comment]
Thank you for applying the changes to master, @nicm, very much appreciated! 😃
I'd like to present to you my work on border style `none` to see if you and I are able find the remaining issue(s) with it and bring it to the finish line.

I'm interested in doing something else related to tmux and have already taken a quick peek at the [Contributing](https://github.com/tmux/tmux/wiki/Contributing) page, is there anything that you find particularly helpful if it would be addressed?
What is you preferred mode of communication? Maybe we can have a conversation about this outside of GitHub issues/PRs?

Yet, I also take interest in (possibly too many 😅) other OSS projects where I'd like to contribute to, so my contributions here may be few and far between.

**Comment by nicm** [comment]
Sure if you open another PR, I'll take a look.

If you want to work on other stuff, I don't know, there are a lot of small things on the todo list which would be mildly useful or that at least one person has asked for...

It would be nice if menus didn't close on resize unless there was no room for them (popups don't).

Making copy mode work in read only mode would be nice (https://github.com/tmux/tmux/issues/3488) - would have to be view only, no copy commands allowed from read only clients.

Stuff like https://github.com/tmux/tmux/issues/3343, https://github.com/tmux/tmux/issues/3114, https://github.com/tmux/tmux/issues/3159, https://github.com/tmux/tmux/issues/3074 would be pretty quick and easy to do. 

https://github.com/tmux/tmux/issues/3166 is more work but would be nice to have, although the path forward is not entirely clear. I think we first wanted to add labels to (nonincremental) search results so you could just straight to them? I would probably add it to the first 36 (0-9,a-z) visible at any time and add a command to jump to one. There could then be fixed bindings (0-9) for the first 10 and a `command-prompt` binding for the others (so you could do 0-9 in one key and the remainder in two). This would mean recalculating the labels every time the screen was scrolled/redrawn, but I think that would be possible. @topcat001 was thinking about this at the time also so he may have some input.

**Comment by nicm** [comment]
You can come on to IRC if you want to talk about this or use the discussions GitHub feature. Or send me an email if you like. There used to be a private team discussions thing but that appears to have been removed.

**Comment by afh** [comment]
Thanks for the inspiration, @nicm. Keeping menus open on resize seems quite useful, I may have a look at that. For now I think I'd like to focus on smaller things to work my way through the tmux code base and familiarise myself more with its concepts and implementation. That said: I made a first attempt at #3343, see #3665 🙂

**Comment by topcat001** [comment]
> @topcat001 was thinking about this at the time also so he may have some input.
I like the way hints are implemented in say qutebrowser. We can use [0-9a-z] for up to 36 matches, or two characters for basically everything that could realistically match on a screen. There could be some rules such as: Use one character <= 36 matches, two chars for more, and avoid using hints for pathological (. for example) cases with regex.

**Pull request closed without merging**
