### PR TITLE
Refactor resize.c

### PR DESCRIPTION
**Pull request by mmjo**
refactoring of default_window_size and recalculate_size

Number of lines in resize.c go from 417 to 322

From issue #2382 
>  > M resize.c (2)
> I think this might be right but the code could probably do with being reorganized. There is a lot of common bits with default_window_size.

Regards, Mike

### CODE REVIEW

**Comment by nicm** [comment]
I like it. Please take a look at this which has some minor tidying and also adds a load of comments: [z.diff.txt](https://github.com/tmux/tmux/files/5259820/z.diff.txt)

**Comment by mmjo** [comment]
On Tue, Sep 22, 2020 at 07:59:24AM +0000, Nicholas Marriott wrote:
> I like it. Please take a look at this which has some minor tidying and also adds a load of comments: [z.diff.txt](https://github.com/tmux/tmux/files/5259820/z.diff.txt)

Will look at it later.

But at first glance, the diff has nothing to do with this resize.c refactoring.
What is it goal?

Regards, Mike

**Comment by nicm** [comment]
Sorry I added the wrong file, I'll fix it later.

**Comment by nicm** [comment]
Try this instead please: [zz.diff.txt](https://github.com/tmux/tmux/files/5265909/zz.diff.txt)

**Comment by mmjo** [comment]
Looks good.

Regards, Mike

**Comment by nicm** [comment]
Great. OpenBSD is about to lock for release but I will apply this once it unlocks.

**Comment by nicm** [comment]
Applied now, thanks!

**Pull request closed without merging**
