### PR TITLE
Format display popup command if single item passed

### PR DESCRIPTION
**Pull request by ClashTheBunny**
I commented on the 3.2 release Q&A here: https://github.com/tmux/tmux/issues/2737#issuecomment-872671383

This would fix that exact comment.

### CODE REVIEW

**Comment by nicm** [comment]
We do not do this for other commands which take shell commands like this, so I think we shouldn't do it here either. You can wrap the command with `run -C` instead.

**Comment by ClashTheBunny** [comment]
I've tried a bunch of things, including adding more paths and escaping and shells and haven't figured it out.  Is there an example?

Would there be the possibility of exposing `format_single_from_target` to the config format, and then there wouldn't be a 'some things like run do templating and most other things don't' situation?

**Comment by nicm** [comment]
run -C "popup 'echo #{version}'"

**Comment by ClashTheBunny** [comment]
:facepalm: I totally was thinking of it backwards.  That works perfectly:
```
bind '`' run -C "display-popup -d '#{pane_current_path}' -xC -yC -w'90%' -h'90%' -E 'tmux attach -t #S-popup || tmux new -s #S-popup'"
```

**Pull request closed without merging**
