### PR TITLE
Clear selection before search

### PR DESCRIPTION
**Pull request by mckellyln**
@nicm fyr

### CODE REVIEW

**Comment by nicm** [comment]
Why would we want to do this?

**Comment by mckellyln** [comment]
If I select a word or line and then just happen to search (/) it highlights the found search string but without this change also leaves my previous selection (totally unrelated to search) highlighted.
It seemed to make more sense to me to clear previous selections so what is highlighted by search is only from search.

**Comment by nicm** [comment]
I don't think this is a good idea, I might want to keep the selection, or be searching while selecting to extend the selection. You can always bind your search keys to clear the selection before searching.

**Comment by mckellyln** [comment]
ok, no problem.  Closing.
Can I bind '/' to prompt for input, then clear-selection, then search ?

**Comment by mckellyln** [comment]
I agree if wanting to highlight until next found item then don't want to clear.

**Comment by mckellyln** [comment]
I think the best answer, at least me, is if the selection is active then don't clear - and search can extend it.  But if the selection is not active (ie was stopped previously) then it should clear.
If I can figure out a binding for the search prompt I'll add this to my config.

**Comment by mckellyln** [comment]
Just a final note, something like this probably works for me:
```
bind-key -T copy-mode-vi '/' command-prompt -p 'search/:' 'if -F "#{selection_active}" "run \"tmux copy-mode ; tmux send -X search-forward %1"\" "run \"tmux copy-mode ; tmux send -X clear-selection ; tmux send -X search-forward %1\""'
```

**Pull request closed without merging**
