### PR TITLE
fixed source-file command causing infinite loops

### PR DESCRIPTION
**Pull request by FadiAfani**
this should address #4215, although using a hash table to track duplicate files might be better

### CODE REVIEW

**Comment by nicm** [comment]
I don't think this need to be that complicated and track every file separately. It just needs a count of how many files deep it is, it doesn't matter if they are different files or the same file. So it can just be a single counter instead of a list of files.

**Comment by FadiAfani** [comment]
> I don't think this need to be that complicated and track every file separately. It just needs a count of how many files deep it is, it doesn't matter if they are different files or the same file. So it can just be a single counter instead of a list of files.

that makes a lot more sense actually, I thought that nesting was to be checked per file, I will try fixing this thanks !

**Comment by nicm** [comment]
Are you still working on this? Thanks.

**Comment by FadiAfani** [comment]
> Are you still working on this? Thanks.

Sorry, I haven't done much with it since last time I got caught up in a few things, I will get back to it if it hasn't been fixed

**Comment by nicm** [comment]
I have applied this now with some changes to tidy it up a bit and to put the depth count inside `struct client` if a client is available. Will be in GitHub later when it syncs up. Thanks!

**Pull request closed without merging**
