### PR TITLE
use utf8proc on platforms with broken wcwidth

### PR DESCRIPTION
**Pull request by joshuarubin**
As discussed in #515, this fixes rendering issues on platforms with broken `wcwidth` implementations (primarily mac) by using utf8proc.

The version of `utf8proc_data.c` differs slightly from the one in the utf8proc project as described in JuliaLang/utf8proc#83.

The difference only ensures that certain characters have width 1 (instead of 2), which means that it is no less correct than the current case of setting a width of 1 whenever `wcwidth` returns `-1`. In most cases, it should be correct much more of the time.

As/if the upstream data file is updated, I will update this pull request, or make a new one as necessary.

### CODE REVIEW

**Comment by nicm** [comment]
No no no, don't copy and paste code from utf8proc - what's the point in that? Link against the library and implement wcwidth() and mbtowc() using it.

There should be no changes to utf8.c.

**Comment by joshuarubin** [comment]
Linking against utf8proc will require changes to anything that packages tmux (like homebrew). Further, there are some problems in utf8proc, as I described, that would make using the upstream version worse than the current hack. Once upstream gets a few issues sorted out, it would be possible, but still seems unnecessary to introduce a new external dependency.

I can move things around with compat to minimize changes to `utf8.c`, but since it imports `<wchar.h>`, it will have to be updated or else there will be multiple definitions of `wcwidth`. Also, not sure how I can redefine `mbtowc` since it is included by `<stdlib.h>`.

And how about giving it a shot before knocking it down. This was not a small amount of work. And it is a whole lot better than the existing hack.

**Comment by nicm** [comment]
Sorry, we are not going to import 1200 lines of code from another
project, we deliberated moved to system wcwidth() to avoid having to
carry around our own Unicode stuff. It is an external dependency or
status quo. Probably I should have been clear on this when I originally
mentioned utf8proc.

If there are currently issues with utf8proc, this should probably just
wait until they are resolved.

There are several options for how we use it, but ideally it should be
entirely contained within compat/ and compat.h with minimal changes to
the main *.c files. It is important not to pollute the main codebase
with #ifdef goo (one or two lines is OK, 10 is not).

We should be able to just link an alternative wcwidth() (it should be a
weak symbol in libc), but if that doesn't work then we can call it
compat_wcwidth() or something and use some small #ifdef to pick the
right function (or do the osdep_* thing we do for event_init()).

**Comment by joshuarubin** [comment]
I updated the PR to use an externally linked utf8proc. It is an opt-in parameter at configure time, not platform dependent.

**Comment by joshuarubin** [comment]
BTW, `utf8.c` is unchanged from `master` and utf8proc is good enough IMO with the minor changes I made (so that emoji and "private use characters" are considered width 1). There is still a corner case of some characters returning width 2 when they should return 1, but that is now in the hands of the utf8proc team and my PR there.

**Comment by nicm** [comment]
This looks good, although I don't like having the code in a header. Doesn't it work if the code goes in a .c file?

**Comment by nicm** [comment]
Also please add a copyright and licence statement to the top of any new file (like the existing files, but obviously with your name). Thanks

**Comment by joshuarubin** [comment]
> Doesn't it work if the code goes in a .c file?

When I put the code in `charwidth.c`, this is the error I get:

```
duplicate symbol _wcwidth in:
    utf8.o
    compat/charwidth.o
duplicate symbol _mbtowc in:
    utf8.o
    compat/charwidth.o
duplicate symbol _wctomb in:
    utf8.o
    compat/charwidth.o
```

Maybe I need to define the functions differently in the header or provide some linker option?

This is the header I used:

```c
#ifndef _CHARWIDTH_H_
#define _CHARWIDTH_H_

#include <wchar.h>

int wcwidth(wchar_t wc);
int mbtowc(wchar_t *pwc, const char *s, size_t n);
int wctomb(char *s, wchar_t wchar);

#endif
```

**Comment by joshuarubin** [comment]
Header file updated with copyright.

**Comment by nicm** [comment]
OK clearly the linker doesn't like it, I think messing with linker options
is not going to be portable. I'm not sure what the tidiest thing to do is,
I'll take a look but I'm out tomorrow so it'll be either Thu or Sat.

**Comment by nicm** [comment]
Here is an updated diff: [utf8proc.diff.txt](https://github.com/tmux/tmux/files/449392/utf8proc.diff.txt)

- Rename the functions to utf8proc_* and put them in compat/utf8proc.c.
- #ifdef them in utf8.c. I thought of calling them osdep_wcwidth or whatever with some ifdef stuff in compat.h but I think this is fine, it is only one line for each and still makes it obvious something is going on without cluttering up the whole show. If we have to do any other funny stuff on other platforms we can reconsider.
- Various style fixes.

Obviously I can only test on Linux, so please test on OS X.

**Comment by joshuarubin** [comment]
OK, changes merged in. Looks good on my side.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by joshuarubin** [comment]
Thanks a bunch 👍  💯 !

**Pull request closed without merging**
