### PR TITLE
Change special key code constants to macros instead of enums

### PR DESCRIPTION
**Pull request by ericvw**
The C standard specifies that enumeration values must fit within a
signed integer.  However, it is implementation defined what type the
compiler may choose.  For the Sun Studio compiler, that type is `int`
whereas `gcc` defaults to `unsigned int`.

This change avoids value overflow by changing the constants to be
defined as macros.

Closes: #2672

### CODE REVIEW

**Comment by ericvw** [comment]
@nicm, this is just a draft/preview of the approach I took.  I had to expand `KEYC_MOUSE_KEY` manually.  Before I continued with getting everything formatted appropriately, I wanted to get your feedback before polishing up the patch.

**Comment by nicm** [comment]
I think it is unnecessary to have an enum at all, why not just:
~~~~
#define KEYC_FOCUS_IN (KEYC_BASE + 0)
#define KEYC_FOCUS_OUT (KEYC_BASE + 1) (or KEYC_FOCUS_IN + 1 if you prefer that)
...
~~~~
Unless you can come up with some cpp trick you will need to expand out `KEYC_MOUSE_KEY` which is unfortunate, but you are having to do that anyway.

Or I wonder if we could squeeze the special keys in somewhere else... there is space in Unicode from 0x80 to 0xa0 and the PUAs at 0xe000, 0xf0000 and 0x100000, but would using them be asking for trouble? Maybe it would be OK, what do you think?

We could swap things around so 0x00 to 0xff are special keys and Unicode is encoded higher up. But it is kind of unintuitive so it seems like it would be really asking for bugs.

**Comment by nicm** [comment]
Maybe we use something like `0x10F000` in the middle of the highest private use area, it kind of seems unlikely anything is going to be sending Unicode keys from the PUA range and will happen to hit the same ones tmux is.

Sorry I only thought of this after you had done this!

**Comment by nicm** [comment]
Something like this, does the compiler still complain?
~~~~
--- a/tmux.h
+++ b/tmux.h
@@ -109,11 +109,16 @@ struct winlink;
 #define VISUAL_ON 1
 #define VISUAL_BOTH 2

-/* Special key codes. */
-#define KEYC_NONE            0x00ff000000000ULL
-#define KEYC_UNKNOWN         0x00fe000000000ULL
-#define KEYC_BASE            0x0001000000000ULL
-#define KEYC_USER            0x0002000000000ULL
+/* No key or unknown key. */
+#define KEYC_NONE            0x000ff000000000ULL
+#define KEYC_UNKNOWN         0x000fe000000000ULL
+
+/*
+ * Base for special (that is, not Unicode) keys. An enum must be at most a
+ * signed int, so these are based in the highest Unicode PUA.
+ */
+#define KEYC_BASE            0x0000000010e000ULL
+#define KEYC_USER            0x0000000010f000ULL

 /* Key modifier bits. */
 #define KEYC_META            0x00100000000000ULL

**Comment by nicm** [comment]
Actually this change is not enough on its own because there are places in the code that check for example `< KEYC_BASE`; these need to change or some Unicode keys will be incorrectly excluded.

**Comment by nicm** [comment]
How about this? [tmux-keys.diff.txt](https://github.com/tmux/tmux/files/6364565/tmux-keys.diff.txt)

**Comment by ericvw** [comment]
> I think it is unnecessary to have an enum at all, […]

I agree the enum is not necessary.  Instead of hardcoding incrementing offsets, I found it easier to use the enum so I could script generating the `#define`'s in my editor.

> How about this?
> [tmux-keys.diff.txt](https://github.com/tmux/tmux/files/6364574/tmux-keys.diff.txt)

I'm trying this right now…

**Comment by ericvw** [comment]
Using the `tmux-keys.diff` patch, I am able to now type in the terminal of the `tmux` session.

However, upon startup I receive the following initial upon invocation before shell initialization:

```
(null):0: unknown key: C-Up                                                                                                   [0/0]
(null):0: unknown key: C-Down
(null):0: unknown key: C-Left
(null):0: unknown key: C-Right
(null):0: unknown key: C-Up
(null):0: unknown key: C-Down
(null):0: unknown key: C-Up
(null):0: unknown key: C-Down
```

**Comment by nicm** [comment]
Hmm that's weird, I'll take a look.

**Comment by nicm** [comment]
Whoops I must have made a change after I tested, can you try this instead please: [tmux-keys2.diff.txt](https://github.com/tmux/tmux/files/6382127/tmux-keys2.diff.txt)

**Comment by ericvw** [comment]
> can you try this instead please: [tmux-keys2.diff.txt](https://github.com/tmux/tmux/files/6382127/tmux-keys2.diff.txt)

This works!  I'm going to locally patch with this for now until a new release is cut.

Thanks for the help because I was getting a bit outside my depth in the special key handling :).

**Comment by nicm** [comment]
Great, I have applied this now, let me know if you see any problems. Thanks!

**Pull request closed without merging**
