### PR TITLE
updated build status url

### PR DESCRIPTION
**Pull request by hackerkid**
updated build status url from ThomasAdam to tmux

### CODE REVIEW

**Comment by hackerkid** [comment]
@nicm why was the pull request closed?. I updated the build status URL.

**Comment by nicm** [comment]
We are not going to add markup to any of the text files. Thanks

**Comment by hackerkid** [comment]
The documentation was more readable in markdown. Thanks for letting know anyway.

**Comment by zxcvbn97** [comment]
Markdown is much more readable in both web-based view and raw text view.
Why is it so difficult to accept changes? Time will tell which format has wider adoption. The same story goes with sourceforge vs. github.

**Comment by notfoss** [comment]
@zxcvbn97 

Plain text is universally accepted. Markup languages have factions. I am more of a reStructuredText person myself ;)

So, it is up to the maintainers to prefer one format over another. Not every project on GitHub should have to use a markup language.

**Pull request closed without merging**
