### PR TITLE
Meson port

### PR DESCRIPTION
**Pull request by Salamandar**
As autotools is a bit shady to use, and it's difficult to have *all* required m4 definitions, I found easier to just port Tmux to the Meson build system.
Here it is, feel free to comment/merge.
I also have a branch that is based on `3.1-rc3` instead of master.

### CODE REVIEW

**Comment by Salamandar** [comment]
I'm trying to add the tests from the `regress` subdir, but they seem to need to be run in the correct order…

**Comment by ThomasAdam** [comment]
No thank you -- I want portable tmux and what's in OpenBSD base to remain as close together as possible, and this change doesn't help with that.

Why do you think this is a good idea?

**Comment by Salamandar** [comment]
> Why do you think this is a good idea?

Well, as I said, recent versions of tmux don't build on CentOS. Meson is really modern-built, faster (well, for a small code base like tmux it's not really important).

> I know how to use it;

That's a fair point. But Autotools and Meson easily cohabit (I ported Gimp, and currently am working on D-bus, and you can guess they don't want to drop autotools).

> it allows you to build in the source directory.

That's actually not a good point, because that "bloats" the source dir. A lot of projects forbid this.

> it is already well tested on all the platforms tmux runs on;

Well, it can't build Tmux 3.x on CentOS, so "well tested" is true for old versions (1.8 here), not recent.

> It doesn't work on OpenBSD which a) doesn't have bison, just yacc b) libevent is in the base system so not in pkg-config c) definitely has VIS_DQ in vis.h.

Yes, the bison bit was unnecessary. About libevent and VIS_DQ, I just recopied the logic of configure.ac

The other issues can easily be fixed once I have a BSD system somewhere.

> It doesn't work on CentOS 7.6: "Meson version is 0.47.2 but project requires >=0.50.0."

That also can be easily fixed by not using one or two recent features.

> And it would be a lot more work to do so than you might think.

Please don't assume what I think ;) As I said I already ported Gimp to Meson, so I think I know what difficulties to expect.

**Comment by nicm** [comment]
I didn't assume what you think, I speculated what you *might* think :-).

> As I said I already ported Gimp to Meson

You didn't say this, or if you did I missed it...

> Well, as I said, recent versions of tmux don't build on CentOS. 

You didn't say this either. tmux definitely builds on CentOS, I use CentOS every day. If you can't get it to work please open a separate issue with make output and config.log.

It is a lot of work to change build system and I don't see any pressing reason to do it. tmux is not a large project with multiple subdirectories and complex interdependencies where I know autoconf is a pain in the arse. For a small project like tmux, it works fine, is well tested, is manageable, and the fact that the tarball can be self-contained and doesn't depend on a particular version of an external build tool is a big advantage to overcome.

**Comment by Salamandar** [comment]
> You didn't say this, or if you did I missed it...

I said it higher on my answer, here : 

> That's a fair point. But Autotools and Meson easily cohabit (I ported Gimp, and currently am working on D-bus, and you can guess they don't want to drop autotools).

> It is a lot of work to change build system and I don't see any pressing reason to do it. tmux is not a large project with multiple subdirectories and complex interdependencies where I know autoconf is a pain in the arse. For a small project like tmux, it works fine, is well tested, is manageable, and the fact that the tarball can be self-contained and doesn't depend on a particular version of an external build tool is a big advantage to overcome.

I guess you could tarball the build directory with the ninja files… But anyways, I understand, you don't want to move from Autotools.

**Comment by nicm** [comment]
Yes, I don't think there are good reasons to change at the moment. Thanks for the suggestion anyway.

**Pull request closed without merging**
