### PR TITLE
support ignore osc 2 after user specify pane title

### PR DESCRIPTION
**Pull request by cache-missing**

### CODE REVIEW

**Comment by nicm** [comment]
This shouldn't be the default, I suggest adding an option `allow-title`. You can either make it `on`/`off` like `allow-rename` and just always forbid it, or have three states`on`/`off`/`unless-user-set` (not wild about the name of the third value).

**Comment by rmGFW** [comment]
> This shouldn't be the default, I suggest adding an option `allow-title`. You can either make it `on`/`off` like `allow-rename` and just always forbid it, or have three states`on`/`off`/`unless-user-set` (not wild about the name of the third value).

ok, i add a new option named `allow-rename-pane`

**Comment by nicm** [comment]
This is not the pane name it is it's title so use a different option name please.

**Comment by cache-missing** [comment]
> This is not the pane name it is it's title so use a different option name please.

how about `allow-rename-title`

**Comment by nicm** [comment]
Also please add the new option to tmux.1.

**Comment by nicm** [comment]
Applied to OpenBSD now with some minor changes, will be in GitHub later. Thanks!

**Pull request closed without merging**
