### PR TITLE
Introducing `-CCC` commandline option #3085

### PR DESCRIPTION
**Pull request by revintec**
https://github.com/tmux/tmux/issues/3085

### CODE REVIEW

**Comment by nicm** [comment]
I think this should be a named flag rather than adding more `-C` (what's next, `-CCCCC`?)

**Comment by revintec** [comment]
ok I'll make it a flag, it seems that I should add them in `server_client_control_flags(...)`?
and I want add another flag e.g. `-f client_cmdline=tmux_cmd_name` that would change the commandline in output like `ps` or `top` from `tmux` to `tmux_cmd_name`, making it easier to manage multiple tmux processes, do you think this feature can be merged?

**Comment by nicm** [comment]
tmux already changes the command name on platforms that support it, you probably just need to add whatever mechanism macOS supports to compat/setproctitle.c.

**Comment by revintec** [comment]
I mean allow user to customize the tmux commandline displayed to the value they choose, instead of the currently hard coded one

**Comment by nicm** [comment]
Are you still working on this?

**Comment by nicm** [comment]
GitHub lost my previous reply to this too. A flag to set the proc title is fine with me, but separate PR please.

**Comment by revintec** [comment]
sorry, since there is a long time without reply, I thought this is not of much interest or is the wrong way to approach this. I've since moved away from this and solved the problem in other ways. thanks for your time, I'll close this issue for now

**Comment by nicm** [comment]
how would that work if tmux cannot change it on macos?

**Pull request closed without merging**
