### PR TITLE
Added math operations to format strings

### PR DESCRIPTION
**Pull request by tculp**
Satisfies #2102

### CODE REVIEW

**Comment by nicm** [comment]
Thanks - looks good, some comments:

- There are only disadvantages to using float here, please use double.

- Please make the additions to format_replace (inside "if (math_expression != NULL)") a new function ("format_replace_equation"? I don't know.)

- snprintf(NULL, 0, ...) isn't portable. You don't need it here anyway, because you can use xasprintf instead and get rid of the .

- If you did have to use them, use xmalloc and xsnprintf please so you don't do anything random if they fail and don't have to check the return value either.

- It is odd to use switch for a simple 0/1 choice, just use if.

- math_number and math_operator should have a format_ prefix like everything else in the file.

- tmux code style:
  - C style comments only please, no //.
  - Space after `switch` etc so `switch (foo)`.
  - Please keep line lengths to 80 characters or less.
  - No {} for single line if/else/for, only if multiple statements inside.

- I think your variable names are far too long... eg I'd change end_character -> endch, buffer_size -> bufsize, use_floating_point_numbers -> usefp, math_expression -> exp or mexp or mathexp, math_precision -> prec or mprec or mathprec. This isn't Java ;-).

- I'm not tied to "e" as the modifier, it was just a suggestion, if you prefer something else then go for it.

**Comment by nicm** [comment]
> snprintf(NULL, 0, ...) isn't portable.

Actually this might be a lie, but anyway you don't need it.

**Comment by tculp** [comment]
It's interesting that fmod isn't available with the libraries travis is using

**Comment by tculp** [comment]
Thanks for the suggestions, I'll work on it

**Comment by nicm** [comment]
A couple of other things:

- Why do you look over the argv? Why not just check for argc == 1 or 2 or 3 and then look at argv[0] for the op, argv[1] for the flags and argv[2] for the precision? Obviously make sure argc <= 3 when you find 'e'.

- Please use strchr not strcmp for the flags - if we add more flags later we want older versions to ignore them.

I'm not sure if yoy could avoid having both int and double to use different arithmetic, maybe you could just use double throughout and then convert to an int if necessary. Not sure if that would always be the same though, I guess it is easy enough to have them separate.

**Comment by nicm** [comment]
fmod probably needs tmux to link against `libm` on some platforms.

**Comment by nicm** [comment]
libm is always available, so don't worry about using fmod - just some platforms roll it into libc, so you don't need an explicit `-lm`.

**Comment by tculp** [comment]
I personally prefer the longer names. I have had difficulty in other parts of the code due to cryptic variable names (like cx), though none of your suggestions are like that, so I'll change them if you wish.

I loop over argv because I didn't see a need to force the order of the flags, and if we add future flags to the expression they won't have to be in a specific order. Though I see strchr may also serve that purpose as well.

I didn't see any other way of cleanly handling the float/int math without duplication and ensuring the result is always correct.

Should I do anything to fix the Travis tests? I assume that would be somewhere in the makefile.

**Comment by nicm** [comment]
Flags should all be in one argument not in multiple, so it matches the
other modifiers. If we don't enforce order of arguments it is hard to add
new arguments, eg if we wanted to have two number arguments we wouldn't be
able to tell which is which.

Yes please change variable names.

You could just store the number as double and cast it eg (long long)a /
(long long)b in the integer case, but I don't mind either way,  union is
fine.

**Comment by nicm** [comment]
-lm will go in Makefile.am, probably in LIBS but I can add it so don't
worry about it if you want.

**Comment by tculp** [comment]
I'll leave the makefile change to you, since I can't easily test it on other systems.

As for the flags, you made the example (in the feature request) of #{e|/|f:...}, which is using multiple arguments, correct? Do you think another syntax would be better?

**Comment by nicm** [comment]
Multiple arguments yes but one for the operator, one for flags, one for
precision. So if we had flags a, b, c it would be eg #{e|+|abc|3}. Each
flag is a single character.

**Comment by tculp** [comment]
Ah, gotcha.

**Comment by tculp** [comment]
What do you think of the behavior of, if floating point numbers are not being used, just flooring the input numbers and result?

**Comment by nicm** [comment]
I don't mind, I'm OK with that or with separate codepaths for fp and !fp, whichever you like.

**Comment by nicm** [comment]
OK, looks good, thanks. I like this a lot. Please take a look at this (diff against clean tree):

[x.diff.txt](https://github.com/tmux/tmux/files/4314288/x.diff.txt)

This has some mostly cosmetic (rather than with fundamental) changes:

- format_math_operator can be function local.

- Move the entire new function before format_replace so it doesn't need a forward declaration, also make it static so it doesn't need to be declared in tmux.h.

- Get rid of the math prefix on most things and make the log and error messages more consistent. "math equation" seems redundant.

- Instead of separate logging for double/integer, just set precision to 0 for integer by default and use %.*f for logging as well.

- Use strtod for doubles, not strtof. Also check it parsed all of the number.

- Free right/left on failure as well - there are "goto fail" after they are allocated.

- Comment, indentation style.

Two things I'm not sure of:

- It isn't really an equation, maybe we should call it something else. Expression? I don't think it matters.

- I forgot that % will need to be escaped as %%. That's a pain. I think we should change it to something else? We aren't tied to symbols so maybe just `m` for modulus?

Other than that this seems good.

**Comment by tculp** [comment]
I do actually prefer expression, as demonstrated by the fact that I kept accidentally typing it instead of equation.

Since I shouldn't free uninitialized left and right, would it be acceptable to have something like
`	freefail:
	free(right);
	free(left);

	fail:
	format_log(ft, "math expression syntax error: %s", copy);
	return (NULL);` and use `goto freefail;` after allocation, and `goto fail;` before?

Also, what are your thoughts on keeping `%` for modulus, but adding `m` as an alternative option? If you don't like that idea, then I'll just make it `m`. Although, apparently c `%` isn't technically the modulus, but the remainder, so maybe `r` would be better.

**Comment by nicm** [comment]
Please see this which adds some of your later changes as well: 

[y.diff.txt](https://github.com/tmux/tmux/files/4316327/y.diff.txt)

I am happy to have `m` or `r` as modulus as well as `%`.

**Comment by tculp** [comment]
I like that, and mixed in several of your changes

**Comment by nicm** [comment]
OK I have applied this to OpenBSD now with a last couple of changes, most notably:

- Instead of dancing around with floor and ceil, just cast to long long and let the compiler do the truncation.

- The result also needs to be truncated, otherwise something like `#{e|/|115|-4}` (which is -28.75) will be -29 rather than -28 when printed with `%.0f`.

This should be in GitHub in the next few hours, let me know if you see any problems.

If you want to do anything further, it would be nice to: 1) have a regression test for these to go in regress/ 2) have some text to add to https://github.com/tmux/tmux/wiki/Formats.

Thanks for working on this!

**Comment by tculp** [comment]
Sounds good! Thanks for your help!

**Pull request closed without merging**
