### PR TITLE
Reply for colour queries for OSC 10 and 11.

### PR DESCRIPTION
**Pull request by mgoral**
Hi, I revisited closed issue #1919 and implemented replies for OSC codes 10 and 11, which seems to be forgotten. Please have a look, thanks!

### CODE REVIEW

**Comment by nicm** [comment]
I'm not wild about this because it only works if the user has set the colour and there is no practical way for it to work otherwise. So is it really that useful? What applications use this?

**Comment by krader1961** [comment]
This is an example of a change that should have been discussed in an issue before a pull-request (i.e., code change) was submitted for review. As @nicm asks, what is the use case? If I create a tmux session, without explicitly setting a background color for the session, what should interrogating the background color return?

This feels like a situation where a feature is implemented as if tmux itself was not present in the use case. Which suggests the person proposing the change does not understand how text terminals, such as a DEC VT100, work or they don't fully understand what it means to multiplex multiple clients onto a virtualized terminal.

**Comment by mgoral** [comment]
@nicm @krader1961: Neovim uses OSC to automatically set its background option (`:set background`), which can be used e.g. by color themes to adapt to either light or dark background.

The problem is that some xterm-compatible terminals already support these codes, but running tmux intercepts these queries. If tmux shouldn't respond to these queries, then why is it allowed to change pane colors by OSC in first place? Why implement OSC codes only partially? After reading #1919 I felt that implementing querying of background/foreground colors is something wanted.

Maybe implementation can be improved for the use case when background isn't explicitly set in tmux by passing through these queries to the underlying terminal. What do you think?

**Comment by nicm** [comment]
It is a lot more useful being able to set than query. You can't pass the query to the underlying terminal because there may be several with different background colours.

**Comment by mgoral** [comment]
Right, so do you see if this can be reliably implemented somehow? Maybe respond only when user sets background in tmux? Or is it better to leave it as it is now (don't respond at all)?

**Comment by nicm** [comment]
The options are to do what your diff does and only respond when the user has set the colour, or to never respond.

**Comment by mgoral** [comment]
@nicm can you have a look if this is now acceptable?

**Comment by nicm** [comment]
Applied now, thanks!

**Pull request closed without merging**
