### PR TITLE
Add abstract socket name support

### PR DESCRIPTION
**Pull request by s1341**
This PR adds support for specifying abstract socket names using `-S`. This allows the use of tmux on unrooted Android.

### CODE REVIEW

**Comment by nicm** [comment]
What does this do and how does it work?

**Comment by s1341** [comment]
It adds support for abstract Unix socket names. See https://man7.org/linux/man-pages/man7/unix.7.html under ‘abstract’. 

It allows one to specify a socket name starting with an ‘@‘. Internally the ‘@‘ gets converted to a null byte. 

Abstract sockets are useful because they do not require a backing file/inode. Additionally, when running on android via adb, the shell does not have permission to create normal Unix sockets, as selinux blocks this. It can, however create abstract sockets. This allows tmux to be used without root via adb.

**Comment by nicm** [comment]
So where does the `@` come into it?

**Comment by nicm** [comment]
So where does the `@` come into it?

**Comment by nicm** [comment]
I mean, did you pick `@`? How are people meant to know to use `@`?

**Comment by nicm** [comment]
I think this needs a check in `server_update_socket` as well.

**Comment by nicm** [comment]
Also the unlink in server_create_socket will need to be conditional I think.

And should we still create /tmp/tmux-XXX? I guess not?

Thanks

**Comment by nicm** [comment]
Oh maybe we don't create it with -S anyway, so that might be OK.

**Comment by s1341** [comment]
‘@‘ is the ‘standard’ way to represent abstract socket names in user interfaces. 

The unlink will silently fail. Also, as far as I can tell, no additional socket is created with ‘-S’. 

I’ll check the ‘server_update_socket’ function.

**Comment by s1341** [comment]
I looked at ‘server_update_socket’. It should just exit early in the case of an abstract socket as stat will fail. I don’t think it requires any special handling.

**Comment by nicm** [comment]
What will happen to `@foo` if I do:
~~~~
touch @foo
tmux -S @foo new
~~~~

**Comment by s1341** [comment]
Ok. Sold. I will make the unlink conditional and add special case code in ‘server_update_socket’.

**Comment by nicm** [comment]
Great thanks.

**Comment by s1341** [comment]
@nicm: Sorry for the delay. Finally got a chance to make the changes we discussed.

**Comment by nicm** [comment]
OK thanks, will take a look. What are the security implications here? What happens if two users open an abstract socket using the same name?

**Comment by s1341** [comment]
Good question. I think it is the same as when using a regular socket path... Not really sure how to go about checking...

**Comment by s1341** [comment]
From here: https://unix.stackexchange.com/questions/579612/unix-domain-sockets-for-non-root-user, it seems that anyone can connect:
```
Unlike regular Unix socket paths, abstract Unix socket names have different semantics, as anybody can bind to them (if the name is not already taken), and anybody can connect to them.

Instead of relying on file/directory permission to restrict who can connect to your socket, and assuming that eg. only root could create sockets inside some directory, you should check the peer's credential with getsockopt(SO_PEERCRED) (to get the uid/pid of who connected or bound the peer), or the SCM_CREDENTIALS ancillary message (the get the uid/pid of who sent a message over the socket).

This (replacing the usual file permission checks) is also the only sane use of SO_PEERCRED/SCM_CREDENTIALS IMHO.
```

**Comment by nicm** [comment]
Well, we can't have that. I think you will need to use `setsockopt(SO_PEERCRED)` when the client connects and make sure the euid is 0 or matches the server. But only do this for abstract sockets because otherwise it will break for people who use shared filesystem sockets.

**Comment by nicm** [comment]
I am concerned about the point in the top comment on this page regarding containers: https://utcc.utoronto.ca/~cks/space/blog/linux/SocketAbstractNamespace?showcomments

But I am not sure this is a genuine issue for tmux since it is not a network program. Does it matter if UID 99 outside one of these containers can access tmux sockets for UID 99 inside and vice versa? Or are they the same and it is not really a security boundary? I don't know anything about this form of Linux container. How do other programs deal with this?

I'm not sure this is going to fly TBH, it seems like abstract sockets are very poorly thought out and very likely to introduce security problems. Can you solve your Android problem another way? Surely there is somewhere to create temporary files?

**Comment by s1341** [comment]
Unfortunately, it's not an issue of having a place to put the file... selinux doesn't allow creation of sockets by the shell user/process at all. In my experience, abstract sockets are the only workable solution.

**Comment by nicm** [comment]
I think what you would need to do is generate a secure (unguessable) name for the abstract socket and store it in a file on disk with appropriate permissions, then later clients could read the file to discover the abstract socket to use, but file system permissions would stop other users from finding it out. But it seems rather complicated to me.

Does Android support multiple users? Maybe we can make this only work on Android.

**Comment by s1341** [comment]
I think making it work only on Android is the way to go. Should I modify the PR to accomplish that?

**Comment by nicm** [comment]
Sure do that and we can see how it looks, thanks.

**Comment by s1341** [comment]
Ok. I'll take a look...

**Comment by s1341** [comment]
I pushed a fix with some conditional compilation for Android.

**Comment by nicm** [comment]
OK, another problem. How does the lock file work? If you give `-S @foo` it is going to create `@foo.lock` in the current directory. What happens if that directory is not writable? What if the client and server are started in different directories? We will need a different way to lock starting the server.

**Comment by s1341** [comment]
hrm. Good point. I think that we'll need to place the lock in `/data/local/tmp`... It is the only temp directory guaranteed to be accessible to the shell user.

**Comment by msharov** [comment]
You do not need the lockfile with abstract sockets. It is one of their best features; the socket is created atomically and deleted when closed, eliminating any race conditions.

Regarding socket access: you really do have to check the connection uid in the server. You can't just generate an "unguessable" socket name because all active abstract sockets can be easily listed with `netstat -l`.

**Comment by nicm** [comment]
Without a lock file, another client could start the server after connect and before bind, causing the original client to fail.

**Comment by msharov** [comment]
You might also consider implementing socket activation (#2398) as an alternative solution. It would allow using abstract sockets and eliminate the race condition you mention. Just a suggestion...

**Pull request closed without merging**
