### PR TITLE
fixes gitignore/*.log and pane-base-index

### PR DESCRIPTION
**Pull request by mmjo**
ignore log files
fix pane-base-index upon start

### CODE REVIEW

**Comment by nicm** [comment]
This is not correct, pane-base-index is for window indexes not window IDs.

**Comment by mmjo** [comment]
Are you perhaps mixing up base-index and pane-base-index?
Or am i getting too old for this? ;)

From the manual:

Available session options:
base-index index
	Set the base index from which an unused index should be searched when a new window is created.  The default is zero.

Supported window options (with setw):
pane-base-index index
	Like base-index, but set the starting index for pane numbers.

**Comment by nicm** [comment]
Oh sorry I meant pane not window, but you are still mixing up index and ID :-). The big numbers you see with C-b q are the pane index, it will change if the pane moves; the ID is a unique number prefixed with %, it will never change.

x

**Comment by mmjo** [comment]
I see; but why not start the ID at pane-base-index too?
With the patch, the first pane gets ID 1, same as it's index.
(with setw -g pane-base-index 1 in ~/.tmux.conf)
Minor detail, though.

**Comment by nicm** [comment]
It isn't the same as its index though because the index can change and the ID will not change. I think it is better to keep them separate.

**Pull request closed without merging**
