### PR TITLE
This is for issue #17

### PR DESCRIPTION
**Pull request by unphased**

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Even if this were OK, you need to update the man page anyway.

**Comment by unphased** [comment]
Yeah I was figuring out how to do that :stuck_out_tongue_closed_eyes:

**Comment by nicm** [comment]
No, we are not going to do this. If you don't want something to be updated, don't put it in update-environment...

**Comment by unphased** [comment]
@nicm There is a real use case for this. Please see #17. I want them to update when attaching. But not when switching sessions from a client.

**Comment by nicm** [comment]
I may accept a flag that bypasses update-environment entirely, but it will need to be added to all commands that use it. -d is a poor choice, prhaps -E.

**Comment by unphased** [comment]
@nicm Very sensible! I'll have a look at the rest of the commands.

**Comment by unphased** [comment]
I would go ahead and do this since it's trivial now that I understand the code (because it's so beautiful :joy:)...

But there's one thing -- `choose-tree.c` runs `switch-client`, so I'm unsure if this means I ought to also add a `-E` flag option to the `choose-tree` command expressly for the purpose of passing it onto `switch-client`.

**Comment by nicm** [comment]
No, leave choose-tree as it is, the command can be specified by the user already.

**Comment by unphased** [comment]
Well that oughta do it

**Comment by nicm** [comment]
Applied with some fixes (flags must be in alphabetical order, new sentence new line in man page, etc).

**Pull request closed without merging**
