### PR TITLE
Make mouse drag end behavior configurable

### PR DESCRIPTION
**Pull request by coderstephen**
This is a pull request to make the behavior of mouse dragging for copy mode configurable. As indicated by requests like #140 and #147, this would be a handy feature in the spirit of making everything in tmux scriptable. Currently, releasing a mouse button after dragging ends the drag event with no further action, and in the case of copy mode, copies the selected bytes into a buffer. This is a logical action, but not customizable. This patch allows this behavior to be customized by rebinding `MouseUp` keys.

**How it works**: A lot of users that have asked for this capability assumed that binding `MouseUpXPane` to something else would control what happens when dragging completes, when in reality such a key is not triggered on release. This patch changes dragging slightly, so that a corresponding `MouseUp` key is always triggered after ending a mouse drag.

**Regressions**: Probably some, but only one that I have noticed -- the behavior of binding to a `MouseUp` key is sort of dual and may or may not be unexpected behavior to users.

Note that default copy mode bindings are added so that `copy-selection` remains the default action when dragging, in line with the current behavior.

I'm not 100% confident in the technical side of this patch, but it is meant to show that it can be done and how. Constructive criticism is very welcome. Also, this is my first contribution to tmux, so everything I say above could be completely wrong. :wink:

### CODE REVIEW

**Comment by nicm** [comment]
I like this. It would be possible to make it a new key (MOUSEDRAGEND1?) but I don't know if there is any advantage.

**Comment by coderstephen** [comment]
@NHDaly I already did set `copy-selection` to the default behavior. :wink: See [mode-key.c#L350](https://github.com/coderstephen/tmux/blob/707b2357b552a26f86b3c895ae313c25b50edf18/mode-key.c#L350) and [mode-key.c#L499](https://github.com/coderstephen/tmux/blob/707b2357b552a26f86b3c895ae313c25b50edf18/mode-key.c#L499). By default `copy-selection` exits copy mode as well.

**Comment by coderstephen** [comment]
@nicm I thought about making it a new key, something like `MouseDragEnd`, and that could easily be done, but as far as I know, `MouseUp` isn't being used all that much since `MouseDown` in general seems to be the one commonly used for handling "click" events.

I suppose, in a single click, it begins with a `Down` event, and ends with an `Up` event, whereas a drag begins by dragging the mouse around with the button down, and ends also whenever the mouse is `Up` as well. Either way seems reasonable though.

**Comment by nicm** [comment]
I have applied this to my next branch with one change (window_copy_drag_release does nothing now, so it can be removed). It will be in master when the OpenBSD tree unlocks and I can apply it there. Thanks!

**Comment by coderstephen** [comment]
Nice! Glad to contribute!

**Comment by cmh** [comment]
@coderstephen Thanks for this contribution! It lets me finally replicate linux "middle mouse to copy" behaviour with `bind-key -t vi-copy -T root MouseUp1Pane copy-pipe "xclip -i -selection primary"`

**Comment by nicm** [comment]
I think I am going to change this to MouseDragEndX because it is trivial to do and there is a use for binding Up and DragEnd differently in copy mode.

**Comment by coderstephen** [comment]
Sounds good to me.

**Comment by NHDaly** [comment]
Hi, what's the status on this? Was it released in `tmux 2.2`? :) Thanks!

+@jvanderpol who was asking me about it.

**Pull request closed without merging**
