### PR TITLE
Support `StatusDefault` mouse target binding

### PR DESCRIPTION
**Pull request by avih**
Following #1649

### CODE REVIEW

**Comment by avih** [comment]
Hmm.. for some reason the "add missing" commit shows at the UI after the "support mouse..." commit, even though it's the earliest of the two. Probably because I authored it later and then moved it to earlier in a `rebase -i`, but it kept the later date...

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Comment by avih** [comment]
Thanks :)

**Comment by avih** [comment]
I noticed that you didn't remove the TODO item. Is that intentional?

**Pull request closed without merging**
