### PR TITLE
Finer control over copy-selection behaviour

### PR DESCRIPTION
**Pull request by hetmankp**
So this is a somewhat ambitious attempt to resolve issue #4123. In order to make the code for this feature simpler there is an overhaul of how the window-copy.c command table deals with arguments so that individual commands don't have to reimplement argument parsing from scratch.

If this change is too broad, it's possible to keep the old approach to argument handling for existing command while only leveraging it for the copy commands, otherwise I can revert to doing something internal to the copy commands only, but this can get a bit ugly given some of them also want the prefix argument.

I've chosen to implement two flags for the copy commands. The original one discussed in #4123, but also one to suppress adding text to the paste buffers. This is both for symmetry but also because the functionality to paste only to the terminal clipboard would be useful to users (like my self) who wouldn't need to reimplement this with an external script given tmux can already do it. The choice of '-C' and '-P' is just what made sense to me but let me know if different letters would fit better here.

Finally, the code for the new feature could be neater if the `struct args` pointer was passed deeper into the call stack. For consistency with the other functions I haven't done that, doing all the argument handling at the same level, but that may have been partially an artefact of the older way argument handling was being done, and it results in some repetition. I think I'd like to push the `cs->wargs` pointer all the way into the window_copy_copy_buffer() function so there's fewer repetitions in the code (replacing the `int set_paste` and `int set_clip` function parameters), if you think that will fit in the style of the codebase.

I can make an attempt to tweak the wiki once this feature is finalised.

### CODE REVIEW

**Comment by nicm** [comment]
Great stuff, this looks good. But incremental search doesn't work anymore. Try:
~~~~
tmux -Ltest -f/dev/null new -d \; set -g mode-keys emacs \; a
~~~~
Then search for something with `C-r` in copy mode - it will search once but pressing `C-r` again will not repeat.

Probably `args_parse` is eating it because of the leading `-` used as a repeat marker for `PROMPT_INCREMENTAL`? Not sure the best way to fix this...

**Comment by hetmankp** [comment]
Oh boy, that's quite the side effect.

I think there is an argument to be made here for expanding the behaviour or `args_parse()` a little. Specifically it should be possible to tell it a particular command doesn't expect any flags so all arguments should be treated as ordinary values.

So instead of the usual empty template `""` (which says all flags should be rejected) we might specify something like `"-"` and give that string a special meaning (resulting in `.args = { "-", 1, 1, NULL }`). Alternatively we could declare a reference to a magic string in memory, so we would have something like this instead: `.args = { ARGS_PARSE_NO_FLAGS, 1, 1, NULL }`. Either way, then it would be easy for me to fix the commands affected by this in `window-copy.c`.

The other option would be to support both the old parsing scheme and the new parsing scheme along side each other. So some commands would be declared like this:

```
	{ .command = "search-backward-incremental",
	  .minargs = 1,
	  .maxargs = 1,
	  .clear = WINDOW_COPY_CMD_CLEAR_ALWAYS,
	  .f = window_copy_cmd_search_backward_incremental
	},
```

And some like this:

```
	{ .command = "copy-selection",
	  .args = { "CP", 0, 1, NULL },
	  .clear = WINDOW_COPY_CMD_CLEAR_ALWAYS,
	  .f = window_copy_cmd_copy_selection
	},
```

Relying on the fact the `struct args_parse` `template` field will be `NULL` if it isn't declared. But this feels a little uglier to me and might lead to a bit more inconsistency in the code.

**Comment by nicm** [comment]
What if you change the `C-r` key binding to add `--`?

**Comment by nicm** [comment]
I think that is OK, I can't see a lot of people having these as custom commands and it is an easy fix if they do.

**Comment by hetmankp** [comment]
Ok I pushed a fix that should take care of all calls to affected commands. I wasn't sure if I should be updating the configs in the `regress/` directory, but it looks like at least one in there had been updated so I did those as well.

**Comment by nicm** [comment]
This looks good to me now, thanks! I will apply it - if you want to be credited let me know your real name or an email address, otherwise I will just mention this issue number.

**Comment by hetmankp** [comment]
Nah if you don't mention Github handles the issue number is fine, glad we got something to solve the issue.

**Comment by nicm** [comment]
Great stuff, I have applied this to OpenBSD now, it will be in GitHub later. I made a couple of very minor changes for line length, let me know of any problems. 

Thanks!

**Pull request closed without merging**
