### PR TITLE
Add -c option to specify starting directory in which run-shell command

### PR DESCRIPTION
**Pull request by caiuswang**
Add -c option to specify starting directory in which run-shell command.  
Associate issure is  [3608](https://github.com/tmux/tmux/issues/3608)

### CODE REVIEW

**Comment by nicm** [comment]
Thanks. Looks good aside from two things:

- You need to copy both strings with `xstrdup` or the result of `args_get(args, 'c')` will be double freed.

- Can you please also update tmux.1 to add this flag?

**Comment by caiuswang** [comment]
> Thanks. Looks good aside from two things:
> 
> * You need to copy both strings with `xstrdup` or the result of `args_get(args, 'c')` will be double freed.
> * Can you please also update tmux.1 to add this flag?

Thanks for pointing out problems. I have fixed it.

**Comment by nicm** [comment]
Looks good, applied to OpenBSD now with minor fixes, will be in GitHub later. Thanks!

**Comment by pataquets** [comment]
Thanks @nicm & @caiuswang!
Browsed around docs trying to figure out the release schedule with no luck.
When will this be available in a release?

**Pull request closed without merging**
