### PR TITLE
Regular expression support for capture-pane

### PR DESCRIPTION
**Pull request by ericpruitt**
I have modified capture-pane to implement regular expression support. This is useful when searching for lines of text in scrollback buffers that have a lot of data in them but only a small subset of the data is of interest to the user. I'm not comfortable with autconf, so I have not made any changes to it. If you would like to merge this change, I would be happy to update the build system (if necessary) if you can provide some general guidance.

### CODE REVIEW

**Comment by nicm** [comment]
I am not convinced by this, what are some use cases where you can't use
grep instead?

**Comment by ericpruitt** [comment]
Nothing in my original message implies I cannot use grep; this is purely a performance optimization. If I dump a large buffer that's thousands of lines long, there's often a very significant amount of lag because tmux has to write out a bunch of data. On top of that, I typically end up ignoring 99% of the output when I grep the scrollback buffer.

**Comment by nicm** [comment]
OK, but you didn't imply that you can either.

How big is your history and how long is the delay?

**Comment by ericpruitt** [comment]
> OK, but you didn't imply that you can either.

Sorry; I thought "This is useful when searching for lines of text in scrollback buffers that have a lot of data in them but only a small subset of the data is of interest to the user" made my use case clear.

> How big is your history and how long is the delay?

The largest scrollback buffer limit I regularly use is 25,000 lines.

I just ran a test with a scrollback buffer populated with `for _ in {1..25000}; echo $LONG_LINE; done`, and this patch was slower than piping to both GNU grep (~2x faster) and whatever grep OpenBSD (only slightly faster) provides by default. As the number of lines is reduced, using the internal regular expressions becomes faster which is what I observed in my earlier tests. I didn't narrow it down to an exact number of lines, but I assume it depends on processor speed; whether or not the grep binary is cached in memory; and if it's not cached, how fast the filesystem its stored on is. I will close this pull request since its efficacy is dubious.

**Pull request closed without merging**
