### PR TITLE
fix grid_reader_cursor_* functions moving over tabs

### PR DESCRIPTION
**Pull request by lexurco**
Hello!

This fixes next-word, next-word-end and previous-word not working correctly on lines with tabs.

Thanks.

### CODE REVIEW

**Comment by lexurco** [comment]
Somehow didn't include these into the first commit: a correct variable name, and a fix for back-to-indentation.

**Comment by lexurco** [comment]
On some further thought, I think something like this might work better. Though I am definitely not a fan of duplicating so much code in the two *_in_set functions. I'll take another look at it later.

[x.diff.txt](https://github.com/user-attachments/files/17818695/x.diff.txt)

**Comment by lexurco** [comment]
It looks better now, I think, but it should probably be tested with UTF-8 characters, particularly in word-separators.

**Comment by lexurco** [comment]
OK, that seems to work with UTF-8 characters too.

**Comment by lexurco** [comment]
This should do it for that bug. It's a bit weird how grid_in_set() can now return >1 for tabs, but 1 for other wide characters. However, I think I'd rather address that when I make it possible for the cursor to snap to the first/last cell of tab (and perhaps any wide character).

**Comment by nicm** [comment]
Good stuff, applied now, thanks!

**Comment by botovq** [comment]
Many thanks for fixing this.

**Pull request closed without merging**
