### PR TITLE
Make select pane return error when encountering window edges.

### PR DESCRIPTION
**Pull request by amosbird**
The whole point of this is to execute custom shell scripts when pane navigation fails.
Specificly, one can move out the terminal emulator and active the next window right to it using window manager scripts. This is also consistent with the behavior of `swap-pane`.

### CODE REVIEW

**Comment by nicm** [comment]
I don't like this, I don't want error messages when I navigate panes and it
is also even more contrary to how tmux usually works (it should probably
wrap at edges to be consistent). It should be fairly simple to write a
script to tell if the current pane is at an edge before you try and move
(use the pane_x window_x and so on formats), so you could do that. Or
maintain this patch privately.

**Comment by nicm** [comment]
I would be open to formats to tell you explicitly if a pane is at the left
right top or bottom which would make things simpler for you.

**Comment by amosbird** [comment]
ok, just add new formats to check if it's at the edge of current window.

**Comment by amosbird** [comment]
Um, may I ask why this is closed?

**Comment by nicm** [comment]
Is anything happening?

**Comment by amosbird** [comment]
Huh? I was thinking you're ok with the new formats.

**Comment by nicm** [comment]
I'm OK with them but someone needs to add them :-). Did I miss that?

**Comment by amosbird** [comment]
Oh, I've added them in this pr.

**Comment by nicm** [comment]
OK you updated the pr I see now I'll look when I get home

**Comment by amosbird** [comment]
cool, thanks!

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Pull request closed without merging**
