### PR TITLE
Check for NULL window_pane

### PR DESCRIPTION
**Pull request by zsugabubus**
There are some missing checks for NULL `wp`.

Crash in `input_csi_dispatch_winops` can be reproduced with: `tmux display-popup printf '\033[t'`.

### CODE REVIEW

**Comment by nicm** [comment]
This is right but I am away from home so I can't apply it, I'll do it when I am back in a few weeks.

**Comment by nicm** [comment]
Applied now, thanks!

**Comment by zsugabubus** [comment]
Do you intentionally omitted the changes in `input_csi_dispatch_winops`?

**Comment by nicm** [comment]
They will be there when it syncs from OpenBSD, it doesn't have SIXEL so the SIXEL bits can go straight into GitHub.

**Pull request closed without merging**
