### PR TITLE
Allow spelling "colour" as "color" in config files

### PR DESCRIPTION
**Pull request by verhovsky**
#2313

Still need to do `ccolour`

### CODE REVIEW

**Comment by nicm** [comment]
This is fine but I don't think there is a sensible way to change the option names.

**Comment by nicm** [comment]
I think you will need to make a function that walks a string and converts "colour" to "color" and use that when looking up an option if the first comparison fails. I'm not really sure it is worth it TBH but it would work.

**Comment by verhovsky** [comment]
Is `ccolour` a configurable thing option? What does it do and how do I configure it? I can't find a tmux config that uses it.

**Comment by nicm** [comment]
I actually think it would be better to have an `alternative_name` member in the table entry (`options-table.c`) and check that if the option isn't found, so something like:
```c
struct options_entry *
options_get_only(struct options *oo, const char *name)
{
    ...

    found = RB_FIND(options_tree, &oo->tree, &o);
    if (found == NULL) {
        for (oe = options_table; oe->name != NULL; oe++) {
                if (strcmp(oe->alternative_name, name) == 0)
                        return (options_get_only(oo, oe->name));
        }
        return (NULL);
    }
    return (found);
}
```
ccolour is a terminal feature (cursor colour), I'd probably just leave it TBH.

**Comment by verhovsky** [comment]
@nicm can you do it please? I don't know C or nroff syntax.

**Comment by nicm** [comment]
Try this please: [c.diff.txt](https://github.com/tmux/tmux/files/5094602/c.diff.txt)

Searching the entire table is too expensive so I added a separate table (`options_other_names`). I only added one option (`display-panes-color`) if you want to add the rest.

Thanks

**Comment by nicm** [comment]
I have applied this now, although I don't think it's necessary to mention this is in tmux.1, so I left that out. Thanks!

**Pull request closed without merging**
