### PR TITLE
Patches for Solaris

### PR DESCRIPTION
**Pull request by dago**
There have been some changes to tmux which prevent compilation on Solaris.
The following changes allow clean compilation on Solaris 10.

### CODE REVIEW

**Comment by nicm** [comment]
Thanks. We will need a compat/strndup.c instead of changing xmalloc.c



On 9 Mar 2017 2:54 pm, "Dagobert Michelsen" <notifications@github.com>
wrote:

There have been some changes to tmux which prevent compilation on Solaris.
The following changes allow clean compilation on Solaris 10.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/tmux/tmux/pull/819
Commit Summary

   - Add replacement if err.h is not available
   - Add missing includes of tmux.h
   - Add replacement for strndup on Solaris as it is no available
   - Include necessary termios.h

File Changes

   - *M* compat.h <https://github.com/tmux/tmux/pull/819/files#diff-0> (15)
   - *M* compat/cfmakeraw.c
   <https://github.com/tmux/tmux/pull/819/files#diff-1> (1)
   - *M* compat/forkpty-sunos.c
   <https://github.com/tmux/tmux/pull/819/files#diff-2> (1)
   - *M* configure.ac <https://github.com/tmux/tmux/pull/819/files#diff-3>
   (1)
   - *M* tmux.c <https://github.com/tmux/tmux/pull/819/files#diff-4> (2)
   - *M* xmalloc.c <https://github.com/tmux/tmux/pull/819/files#diff-5>
   (21)

Patch Links:

   - https://github.com/tmux/tmux/pull/819.patch
   - https://github.com/tmux/tmux/pull/819.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/pull/819>, or mute the thread

**Comment by nicm** [comment]
Also note we will need a copyright and license (or a public domain
declaration) on the strndup code, just stating the author is not enough.


On 9 Mar 2017 3:07 pm, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

Thanks. We will need a compat/strndup.c instead of changing xmalloc.c



On 9 Mar 2017 2:54 pm, "Dagobert Michelsen" <notifications@github.com>
wrote:

There have been some changes to tmux which prevent compilation on Solaris.
The following changes allow clean compilation on Solaris 10.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/tmux/tmux/pull/819
Commit Summary

   - Add replacement if err.h is not available
   - Add missing includes of tmux.h
   - Add replacement for strndup on Solaris as it is no available
   - Include necessary termios.h

File Changes

   - *M* compat.h <https://github.com/tmux/tmux/pull/819/files#diff-0> (15)
   - *M* compat/cfmakeraw.c
   <https://github.com/tmux/tmux/pull/819/files#diff-1> (1)
   - *M* compat/forkpty-sunos.c
   <https://github.com/tmux/tmux/pull/819/files#diff-2> (1)
   - *M* configure.ac <https://github.com/tmux/tmux/pull/819/files#diff-3>
   (1)
   - *M* tmux.c <https://github.com/tmux/tmux/pull/819/files#diff-4> (2)
   - *M* xmalloc.c <https://github.com/tmux/tmux/pull/819/files#diff-5>
   (21)

Patch Links:

   - https://github.com/tmux/tmux/pull/819.patch
   - https://github.com/tmux/tmux/pull/819.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/pull/819>, or mute the thread

**Comment by nicm** [comment]
The other changes look OK.


On 9 Mar 2017 3:08 pm, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

Also note we will need a copyright and license (or a public domain
declaration) on the strndup code, just stating the author is not enough.


On 9 Mar 2017 3:07 pm, "Nicholas Marriott" <nicholas.marriott@gmail.com>
wrote:

Thanks. We will need a compat/strndup.c instead of changing xmalloc.c



On 9 Mar 2017 2:54 pm, "Dagobert Michelsen" <notifications@github.com>
wrote:

There have been some changes to tmux which prevent compilation on Solaris.
The following changes allow clean compilation on Solaris 10.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/tmux/tmux/pull/819
Commit Summary

   - Add replacement if err.h is not available
   - Add missing includes of tmux.h
   - Add replacement for strndup on Solaris as it is no available
   - Include necessary termios.h

File Changes

   - *M* compat.h <https://github.com/tmux/tmux/pull/819/files#diff-0> (15)
   - *M* compat/cfmakeraw.c
   <https://github.com/tmux/tmux/pull/819/files#diff-1> (1)
   - *M* compat/forkpty-sunos.c
   <https://github.com/tmux/tmux/pull/819/files#diff-2> (1)
   - *M* configure.ac <https://github.com/tmux/tmux/pull/819/files#diff-3>
   (1)
   - *M* tmux.c <https://github.com/tmux/tmux/pull/819/files#diff-4> (2)
   - *M* xmalloc.c <https://github.com/tmux/tmux/pull/819/files#diff-5>
   (21)

Patch Links:

   - https://github.com/tmux/tmux/pull/819.patch
   - https://github.com/tmux/tmux/pull/819.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tmux/tmux/pull/819>, or mute the thread

**Comment by nicm** [comment]
If you can't easily find a suitable strndup let me know and I'll just write
one.

**Comment by nicm** [comment]
Actually, I suggest we just use this:

**Comment by dago** [comment]
Fine with me.

**Comment by dago** [comment]
Downstream request for update at https://www.opencsw.org/mantis/view.php?id=5299

**Comment by nicm** [comment]
I have applied these, with some changes:

- implement err() and friends as C functions not macros; build tested only;
- it is no longer OK for compat/*.c to include tmux.h, I think you are just after termios.h where you add it;
- add strnlen and strndup from OpenBSD.

**Comment by dago** [comment]
I verified that it builds cleanly on Solaris, I'll close the pull request.

Thanks! -- Dago

**Pull request closed without merging**
