### PR TITLE
Make window resize evaluation lazy.

### PR DESCRIPTION
**Pull request by xim**
Ref tmux/tmux #1779

### CODE REVIEW

**Comment by nicm** [comment]
I think this is OK, there is no harm with it sitting with PANE_RESIZE set. This is slightly simpler and also checks if the session is attached:
~~~~
--- server-client.c     25 May 2019 07:18:20 -0000      1.285
+++ server-client.c     6 Jun 2019 08:41:51 -0000
@@ -1339,9 +1339,18 @@ static void
 server_client_check_resize(struct window_pane *wp)
 {
        struct timeval   tv = { .tv_usec = 250000 };
+       struct winlink  *wl;

        if (!(wp->flags & PANE_RESIZE))
                return;
+
+       TAILQ_FOREACH(wl, &wp->window->winlinks, wentry) {
+               if (wl->session->attached != 0 && wl->session->curw == wl)
+                       break;
+       }
+       if (wl == NULL)
+               return;
+
        log_debug("%s: %%%u resize to %u,%u", __func__, wp->id, wp->sx, wp->sy);

        if (!event_initialized(&wp->resize_timer))

**Comment by xim** [comment]
I placed the logic outside the `server_client_check_resize` function so it isn't evaluated per pane. 
c9871a9  is implemented exactly as you proposed, 
4cad13a should be better (unless I misunderstood what happens with that `wp->flags &= ~PANE_REDRAW;` in `server_client_loop`)

**Comment by nicm** [comment]
I like this, will test it for a while.

**Comment by nicm** [comment]
I have applied this now. Thanks!

**Pull request closed without merging**
