### PR TITLE
Create new raw copy/pipe/append commands

### PR DESCRIPTION
**Pull request by FractalBoy**
Addresses #3505.

This is not yet complete, but I am creating a pull request just to make sure I'm staying on the right track.

### CODE REVIEW

**Comment by nicm** [comment]
Looks sensible to me so far.

**Comment by FractalBoy** [comment]
The actual copying does not seem to be working - can you provide any guidance on the correct arguments to pass to `grid_string_cells`?

**Comment by FractalBoy** [comment]
No, I get a buffer missing one character with no escape sequences, so it seems like maybe I need to add 1 somewhere.

The fact that I'm missing a flag explains the missing escape sequences.

**Comment by nicm** [comment]
Well I don't mind having `copy-escape-sequences` option is that less useful than different commands?

**Comment by nicm** [comment]
Are you still working on this? Thanks.

**Comment by FractalBoy** [comment]
Yes, just haven't had a chance to work on it in a bit.

**Comment by nicm** [comment]
OK no worries.

**Comment by FractalBoy** [comment]
Okay, this seems to mostly work now, but I'm still having an issue getting the final character of my string.

For example, when I do `printf "\033[01;32mtest\033[00m\n"`, then highlight the resulting string, I get this on my clipboard:

`\033[1m\033[32mtes`

I would expect to get the `t` at the end of the word, and it would be nice to get the closing sequence but I don't think that's possible since I'm not highlighting past that.

**Comment by nicm** [comment]
I am not seeing this problem, when I copy your example, I get:
```
$ tmux lsb
buffer3: 13 bytes: "\033[1m\033[32mtest"
```
Which looks fine to me. How are copying?

For the closing sequence you could add a flag to make `grid_string_cells` emit a reset at the end of the string.

It would be nice if `window_copy_copy_line` used `grid_string_cells` for the normal case as well (but that might need a flag to map ACS characters). You don't need to worry about that, we can do that separately.

**Comment by FractalBoy** [comment]
I was getting it through OSC 52 - perhaps my terminal (Windows Terminal) isn't handling it well then.

**Comment by nicm** [comment]
I think it is a bug in your terminal because when I try OSC 52 (although I need a fix to make it work at all with `send -X` rather than a key binding), it has the complete text.

**Comment by nicm** [comment]
I think this is OK but I have been unwell so I haven't been able to look at it again, I'll try and get to it in the next couple of weeks.

**Comment by FractalBoy** [comment]
I haven't quite finished it - still much documentation to do, and I would still like a way to change the default for all copy-* command to "raw" mode. Haven't had time to work on it lately.

**Review by CleanSl8 — APPROVED** [review]

**Comment by nicm** [comment]
I'm going to close this but do comment again if you get back to it and I will reopen.

**Pull request closed without merging**
