### PR TITLE
find: rename relative left/right to avoid ambiguity

### PR DESCRIPTION
**Pull request by mathstuf**
---
Feel free to use something more descriptive than `r` as well when applying (or I can respin).

### CODE REVIEW

**Comment by nicm** [comment]
I think this is more confusing, and we call them left/right/up/down in other places too.

**Comment by mathstuf** [comment]
True, but there's also `{left}` meaning left-most pane. The one meaning left-of-focused never gets hit.

**Comment by nicm** [comment]
Ah yes, that is a problem. I don't like rleft and rright though, maybe
the top/bottom/left/right/top-left/etc should be prefixed with window, so like
window-top etc?

**Comment by mathstuf** [comment]
That can work, but seems a little wordy. What about `{left-of}` for the relative one (`{up}` and `{down}` are already obviously relative to me)?

**Comment by nicm** [comment]
Yes *-of sounds ok but I think they should all be consistent.

**Comment by mathstuf** [comment]
Renamed.

**Comment by mathstuf** [comment]
Also, do you still prefer `format-patch` and `send-email`?

**Comment by nicm** [comment]
Email is better or link me to the patch please.

**Comment by mathstuf** [comment]
Patch sent to the list.

**Pull request closed without merging**
