### PR TITLE
Fix libevent broken link

### PR DESCRIPTION
**Pull request by rafaeleyng**

### CODE REVIEW

**Comment by rafaeleyng** [comment]
The link was broken when I opened the pull request.
Actually I've tried the link in the README again today and it was redirecting to the link that I've changed to.

**Comment by nicm** [comment]
Applied thanks

**Comment by rafaeleyng** [comment]
No offense intended in asking, but any particular reason for not accepting the pull request?

**Comment by nicm** [comment]
I don't want to apply pull requests.

**Comment by rafaeleyng** [comment]
:broken_heart:

**Pull request closed without merging**
