### PR TITLE
test workflow

### PR DESCRIPTION
**Pull request by jiahujiahu**

### CODE REVIEW

**Comment by krader1961** [comment]
What are you doing? You're generating a lot of noise in my inbox.

**Comment by krader1961** [comment]
You're driving me insane. Is there some reason you can't test these changes without pushing them upstream to the Tmux project?

**Comment by jiahujiahu** [comment]
> You're driving me insane. Is there some reason you can't test these changes without pushing them upstream to the Tmux project?

I am sorry sir. Just noticed that my action cause a merge for the master branch, I just thought that will push the changes to my cloned branch.

**Comment by nicm** [comment]
Please stop opening PRs until you have something to submit and at that point please open a PR with that change any nothing else.

**Pull request closed without merging**
