### PR TITLE
Improve README file

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Hello,

I was reading your messages on #1732 and I thought it was time to try and contribute to tmux myself. Yes I had issues with the latest release and yes I also thought the changelog wasn't verbose enough about it, but you make valid points, it's one thing to complain, and another to actually contribute with testing, documentation and the rest, so here I am! :)

*Side note: my first simili-contribution to this project was creating the [tmux archwiki page](https://wiki.archlinux.org/index.php/Tmux) more than 9 years ago! :D*

Because I don't know how to write C code, my contribution is on the README.

See the before/after below:

Montage-1

Isn't it more sexy? 99% of users reading this file will do it from the GitHub page, so there is no need for keeping it barebones. And it's still very readable in text mode (the advantage of markdown!).

Here is the commit message:

* Use Markdown syntax: readable in text mode and prettier when seen on
GitHub
* Create chapters/headers for clearly separating paragraphs
* Use GNU/Linux instead of just Linux
* Update links for ncurses and libevent
* Use syntax highlighting for code blocks (and drop the '$' which is
confusing for some users)
* Group the contributing bits together and mention the CONTRIBUTING file
* Add a link for the ISC license

Cheers :)
~Nico

PS: yes users will copy paste with the `$` sign and not understand why it doesn't work. Believe it. Also, it makes it easier for copy pasting ;)

### CODE REVIEW

**Comment by nicm** [comment]
Thanks for doing this I appreciate the effort but I don't think it's a good idea to ship complex rich text files in the tmux tarball. Most people will be reading this in a terminal text editor not in a web browser so I don't think any form of markup is helpful, especially not for such a short file.

If you could separate out your text changes (but not GNU/Linux please I don't like that), I will apply those.

Possibly the marked up version could be kept and go in a subdirectory if it would be useful.

**Comment by nicm** [comment]
Can GitHub be told to look in a subdirectory for the README file it displays? Then we could put a marked up version in without cluttering up the source tree. It would be nice to put CONTRIBUTING away as well.

**Comment by ThomasAdam** [comment]
On Fri, May 10, 2019 at 03:05:28PM -0700, Nicholas Marriott wrote:
> Can GitHub be told to look in a subdirectory for the README file it
> displays? Then we could put a marked up version in without cluttering up the
> source tree. It would be nice to put CONTRIBUTING away as well.

I don't think so.  But a symlink might do it from the top-level directory.

-- Thomas

**Comment by nicm** [comment]
Yes it says: "If you put your README file in your repository's root, docs, or hidden .github directory..."

So just need to test to see if a file in .github will be used instead of the root README.

**Comment by nicm** [comment]
Well a symlink doesn't help because if is still cluttering the top level source directory with GitHub files. I'll test tomorrow and see if .github/README{,.md} works and if so then @NicolasCARPi's version can go there.

**Comment by ThomasAdam** [comment]
This worked:

https://github.com/ThomasAdam/tmux/tree/ta/test

So it looks like you can.  I'm happy to pick this up if you like, @nicm

**Comment by nicm** [comment]
Great stuff, it would be nice to have the fancy README in there and the
same text in the plain 80-column no-markup /README.

It would also be good to move CONTRIBUTING (and ISSUE_TEMPLATE if possible)
in there and add mark up to it.

**Comment by NicolasCARPi** [comment]
I'm making another PR with README in .github and also moving  the contributing file and add an issue_template. Stay put :)

**Comment by NicolasCARPi** [comment]
See #1735

**Pull request closed without merging**
