### PR TITLE
Add persist-without-sessions server option

### PR DESCRIPTION
**Pull request by Shados**
Defaults to `off`, if set to `on` it causes the tmux server process to keep running even without any active sessions.

## Use Case
My motivation for this change is that I'd like to run a tmux server as a systemd user service, and while I can currently do so by having it spawn an empty or default session, this is kind of a hack.
I typically start a new session per terminal rather than defaulting to re-connecting to an existing session, and having an extra session hanging around purely to keep the server alive is... somewhere between annoying and potentially confusing. 

More generally, the benefits of running the server under some form of service management are:
- If using systemd, can persist across logouts (if lingering is enabled for the user, and generally only relevant if logind is configured with `KillUserProcesses=yes`)
- Can use a different configuration file location than the default, without having to pass it in the command line directly or use an alias
- Can have the tmux server ready and waiting before any terminal or ssh sessions need to use it, effectively eliminating server startup time (in my experience this is trivial, but I know it affects some people on older hardware more noticeably)

There are at least a few other people who want this behaviour, based on a couple of previous issues where people were confused as to the behaviour of the `exit-unattached` option (namely #182 and #512).

## Notes

- I've only tested this out under Linux (NixOS, specifically)
- The unmodified `list-sessions` code called against an empty server simply results in no lines being printed, which seems suitable to me

----------

As an aside, is there anything in the way of development or high-level design documentation for tmux? I noticed the presentations but haven't done more than glance through them yet. 

I'm asking because I'm interested in contributing more generally; I haven't written much C in a long time, and am feeling oddly nostalgic. What I've seen of tmux's code looks pretty clean to me, so it's an attractive option as something to work on.

### CODE REVIEW

**Comment by nicm** [comment]
I would invert the sense of this and call it exit-no-sessions (default to on) to match exit-unattached.

**Comment by Shados** [comment]
Grouping it with exit-unattached makes sense to me, but I think exit-no-sessions is pretty unintuitive as far as option names go. How about maybe 'exit-empty'?

**Comment by nicm** [comment]
OK

**Comment by Shados** [comment]
OK, I've changed it.

**Comment by nicm** [comment]
Applied to OpenBSD now, will be in GitHub later. Thanks!

**Pull request closed without merging**
