### PR TITLE
Organize a bunch of headers into compat.h

### PR DESCRIPTION
**Pull request by skyline75489**
Supports #2575

### CODE REVIEW

**Comment by skyline75489** [comment]
@nicm How do like the approach of this PR? Believe me I hate `#ifdef` just as much as you do. We probably still gonna have them but I'll try limit the usage of `#ifdef` to the minimum.

**Comment by nicm** [comment]
I think you should make `compat-win32.h` for the structs and whatnot.

I don't mind moving headers about if necessary but I won't do it until you have something working and we can see what it looks like.

**Comment by skyline75489** [comment]
Well I have to be honest, there's a loooong way before I can visually have "something working". The code compiles with a bunch of `#ifdef`. Linking still fails, because there's a lot of things need to be ported to Windows.

Overall I think the porting process can be divided into the following steps:

* [X] Make it compile with all the header tweaks. 
* [ ] Port tty related code with ConPTY
* [ ] Port socket related code with WinSock
* [ ] Port event related code with libevent if possible
* [ ] Port everything else
* [ ] Compile & Link should work.
* [ ] It would like 100% crash but let's see how to fix them
* [ ] Fix a lot of things that does not work
* [ ] Maybe we can make it run if nothing blocks it

 It's like my day 2 of the porting process, so I think I can call it a day by just passing the compilation.

**Comment by skyline75489** [comment]
Having `compat-win32.h` is good idea. Will do. 

My local repo is a mess (but hey, it compiles), so I just picked the header changes here.

**Comment by nicm** [comment]
Yes I'm sure it will need a lot of tidying to be finished, do feel free to feed back smaller changes if they are improvements for all platforms but I don't want to do all these header changes or start adding `#ifdef WIN32` right now. Thanks

**Comment by skyline75489** [comment]
Would it be OK if I still do the imports organizing, which is in fact "improvement for all platforms"? I found some imports should be decided by `compat.h` for better compatibility. If it's cool with u, I'll drop the win32 things in this PR and only leave the reorganizing .

**Comment by nicm** [comment]
What do you mean imports?

**Comment by skyline75489** [comment]
I mean `#includes`. Sorry, wrong language (`#Objective-C`). Pretty must just to have most Linux headers in `compat.h`, and drop the Win32 things

**Comment by nicm** [comment]
I don't want to move them all about at the moment, they are fine as they are for every Unix platform.

I meant more if you have to move code around or add helper functions or anything that can apply to any platform, rather than stuff that is only needed for Windows.

We can move the includes around pretty easily later and it would be a good first step but I'd like to wait until you have something a bit further along.

**Comment by skyline75489** [comment]
That's very fair. Thanks for the feedback. I'll close this for now.

**Comment by nicm** [comment]
Great thanks, let me know if you run into any problems or have any questions. If you get it building and working I can take a look and we can work out how best to tidy it up to merge it at that point.

**Pull request closed without merging**
