### PR TITLE
Add options and arguments for display-menu to set border, border style, and style

### PR DESCRIPTION
**Pull request by afh**
~~:warning: The merge base of this PR should be [`afh:afh-popup-style-arguments`](https://github.com/afh/tmux/tree/afh-popup-style-arguments) from #2931 instead of [`tmux:master`](https://github.com/tmux/tmux).
:information_source: To see only the relevant changes please compare [`afh:afh-popup-style-arguments` with`afh:afh-menu-style-opts-args`](https://github.com/afh/tmux/compare/afh-popup-style-arguments...afh:afh-menu-style-opts-args?expand=1).~~ Update: #2931 has been applied, so master as a merge base for this PR is now correct 🎉 

This PR brings the same styling capabilites from popup to menu.

To test:
* Build and run tmux `./tmux -vv -f/dev/null -Ltest`
* Set menu-border-lines, menu-style options and display menu (see `test_menu_style.sh` below)
* Use `-B`, `-b`, `-s, `-S` arguments when displaying a menu (see `test_menu_style.sh` below)

<details><summary><code>test_menu_style.sh</code></summary>

```
#!/bin/ksh

./tmux set -gwU menu-border-lines
./tmux set -gw menu-border-lines double
./tmux set -gw menu-border-style fg=black,bg=yellow
./tmux set -gw menu-style fg=magenta,bg=cyan
./tmux set -gw mode-style fg=yellow,bg=black
./tmux menu -T 'Styled via Options' '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' baz '' ''

./tmux menu -B -T 'Styled via Options' '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' baz '' ''

./tmux menu -b heavy -S fg=blue,bg=red -s fg=magenta,bg=cyan -T 'Styled via Arguments' foo '' '' -bar '' '' '' baz '' ''

./tmux menu -B -b heavy -S fg=blue,bg=red -s fg=magenta,bg=cyan -T 'Styled without Border' foo '' '' -bar '' '' '' baz '' ''
```

</details>

| | |
| --- | --- |
| Styled with Options | 2021-10-23-101801_905x562_scrot|
| Styled without Border | 2021-10-23-103011_905x562_scrot|
| Styled with Arguments | 2021-10-23-101809_905x562_scrot|
| Styled without Border | 2021-10-23-101815_905x562_scrot|

### CODE REVIEW

**Comment by nicm** [comment]
Are you still working on this? :-)

**Comment by afh** [comment]
Apologies for the late response, @nicm. My day job has kept me busy the past two weeks. I made good progress already, let me take this to the finish line, so that it works properly and we can then look at improvements regarding the implementation :)

**Comment by nicm** [comment]
Are you still working on this?

**Comment by rwp0** [comment]
@afh please respond as we desire this feature a lot 🙂

**Comment by afh** [comment]
Apologies everyone (especially to @nicm) for having falling silent on this and other contributions to tmux. I had bitten off more than I could chew, felt rather overwhelmed by my obligations, and needed some time for myself.

Let me get my tmux dev setup up and running on my new machine, see what the state of this PR is, and what local changes I have. I remember having problems with edge cases when the menu was was placed above/below/next to tmux window borders/bars.

Out of curiosity @rwp0: Who is 'we' and what will you use this feature for?

**Comment by rwp0** [comment]
> Apologies everyone (especially to @nicm) for having falling silent on this and other contributions to tmux. I had bitten off more than I could chew, felt rather overwhelmed by my obligations, and needed some time for myself.
> 
> Let me get my tmux dev setup up and running on my new machine, see what the state of this PR is, and what local changes I have. I remember having problems with edge cases when the menu was was placed above/below/next to tmux window borders/bars.
> 
> Out of curiosity @rwp0: Who is 'we' and what will you use this feature for?

Tmux users, for customization

**Comment by afh** [comment]
Thank you for your kind words, Nicholas 😌

**Comment by afh** [comment]
I've taken a close look at the state of this PR and I believe the remaining main issue is positioning a borderless menu. The concept of borderless menus has not existed in tmux until this PR, so I think code always a assumes a one row / column border. I looked into the `format*.c` related code, but was unable to figure out how to best change it. Especially as that code seems to be unaware of any border styling, which I believe needs to be taken into account to position borderless menus properly.

@nicm if you would be so kind to lend your expertise here and provide some information and/or ideas on how to best move forward here, that would be greatly appreciated.

| Issues | Screenshot |
| --- | --- |
| ➊ When the title is shorter than longest menu entry the menu title background is not set properly<br><br> ➋ On the sides tmux thinks there should be a border and leaves empty space. In my mind the menu should be shifted to the left by one column <br><br> ➌ At the bottom tmux thinks there should also be a border and shows empty space. I think the menu should sit flush on top of the menu bar in this configuration |  |
| When no title is given tmux tries to draw an empty menu title |  |

Here's the script I use for testing. It fills the terminal with the `·` character which helps in identifying if a tmux border has an "invisible", i.e. the same colour as the terminal background, border and the displays several menus styled differently to identify unhandled edge cases (see above).

<details><summary><code>test_menu_style.sh</code></summary>

```sh
#!/bin/ksh

set -A size $(stty size)
awk -vc=· -vr=${size[0]} -vl=${size[1]} 'BEGIN{for(i=0;i<r;i++) for(j=0;j<l;j++) printf c}'

./tmux set -gwU menu-border-lines
./tmux set -gw menu-border-lines double
./tmux set -gw menu-border-style fg=black,bg=yellow #,fill=green
./tmux set -gw menu-style fg=magenta,bg=cyan #,fill=blue
./tmux set -gw mode-style fg=yellow,bg=black #,fill=red
#./tmux menu -T 'Styled via Options' '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' baz '' ''

./tmux set status-position bottom
./tmux menu -B -T 'Styled via Options' -x P -y P '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' 'phoofies froobicate spam eggs zap' '' ''
./tmux menu -B -T 'Styled via Options' -x R -y P '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' 'phoofies froobicate spam eggs zap' '' ''
./tmux set status-position top
./tmux menu -B -T 'Styled via Options' -x W -y S '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' 'phoofies froobicate spam eggs zap' '' ''
./tmux menu -B -T 'Styled via Options' -x R -y P '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' 'phoofies froobicate spam eggs zap' '' ''
./tmux menu -B -T 'Styled via Options' -x C -y C '#[fg=red,bg=blue]foo' '' '' -bar '' '' '' 'phoofies froobicate spam eggs zap' '' ''


#exit
./tmux menu -B '#[fg=red,bg=blue]Styled via' '' '' -Options '' '' '' 'No Title' '' ''


./tmux menu -b heavy -S fg=blue,bg=red -s fg=magenta,bg=cyan -T 'Styled via Arguments' foo '' '' -bar '' '' '' baz '' ''

./tmux menu -B -b heavy -S fg=blue,bg=red -s fg=magenta,bg=cyan -T 'Styled without Border' foo '' '' -bar '' '' '' baz '' ''
```

</details>

**Comment by nicm** [comment]
I'm not really clear what you're asking here. It would be OK with me if borderless menus had no border at all.

**Comment by nicm** [comment]
I'm going to close this for the moment but do let me know if you want to revisit it.

**Comment by afh** [comment]
Sounds good it's been lingering for a long time. I'm happy to revisit, but uncertain how to best proceed. Any ideas?

**Comment by nicm** [comment]
I would probably split it up to three diffs one for the menu style, one for the border style and one for the border lines.

The first two look to be pretty simple so I would do one or both of them first.

For border lines, I would just forget borderless menus for now so we don't need need to worry about the size and positioning changing and just give the same options as pane borders.

Then once that is in if you want to do borderless menus, you could add them separately.

**Comment by afh** [comment]
Thanks for the helpful suggestion, @nicm, very much appreciated! I'll look into splitting the work in more manageable chunks and open PRs accordingly. At this point I'm uncertain when I can find the time to do so.

**Comment by afh** [comment]
Thank you for the helpful suggestion about how to best continue on this, @nicm :pray:
I went ahead and created 3 follow-up PRs (#3648, #3649, #3650) and look forward to continue the conversation over there.

**Comment by nicm** [comment]
Thanks for this - I am tied up this week and then I shall be on holiday next week, so I'll take a look at these when I am back the week after.

**Comment by afh** [comment]
Thanks for the heads up, @nicm. Given that this PR is almost 2 years old a few more weeks won't hurt… Have a pleasant holiday! 😎⛱️🌞

**Pull request closed without merging**
