### PR TITLE
Haiku first support.

### PR DESCRIPTION
**Pull request by devnexen**
forkpty compat layer based on hpux mainly minus few unsupported ioctl calls.

### CODE REVIEW

**Comment by nicm** [comment]
Thanks:

- Does this work? I'm not going to apply a work-in-progress.

- Don't do `#ifdef __HAIKU__` for `IMAXBEL` or other termios bits. Please define the missing bits to 0 in compat.h like we do for `ECHOPRT`.

- Don't use `AC_DEFINE` for compiler flags like `_BSD_SOURCE`, add it to `AM_CPPFLAGS` in Makefile.am like we do for NetBSD.

- Please use C style comments (`/* ... */`) not C++ style (`//`);

**Comment by devnexen** [comment]
Yes it does. addresses the rest of your remarks.

**Comment by nicm** [comment]
Great stuff - I have applied this now with a few minor tweaks, let me know if I have introduced any mistakes. Thanks!

**Comment by devnexen** [comment]
so far so good ;-)

**Pull request closed without merging**
