### PR TITLE
Apply patch for OSC 8 hyperlinks

### PR DESCRIPTION
**Pull request by sencer**
Is there a reason this patch is not included in HEAD?

### CODE REVIEW

**Comment by nicm** [comment]
It is not complete. Hardly any terminals support it. Hardly any applications support it.

**Comment by dufferzafar** [comment]
For people who need more context, please see: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

It has a list of terminals & applications that do support it. @nicm I think saying "hardly any" for that list doesn't seem justified.

**Comment by glensc** [comment]
@dufferzafar: I think a correction is in order: "doesn't seem justified anymore"

for posterity, the original PR seems to be at:
- https://github.com/tmux/tmux/issues/911

@sencer: you should remove your "this patch" change from the readme.md changes, if you want this to be merged. i'm pretty sure upstream will never accept it in this form. in fact, you should never create pull requests from your master branch as the branch is directly linked with PR so you can't modify the branch for your own purposes.

**Comment by sencer** [comment]
@glensc I added that part after @nicm's response.

**Comment by glensc** [comment]
@sencer remove it if you want the change to be merged. it describes this specific pull request, so such text belongs to the commit message and/or pr body, not the final readme (result of the merge), as that would describe the project.

**Comment by yesnomaybeyes** [comment]
> It is not complete. Hardly any terminals support it. Hardly any applications support it.

gcc, coreutils, and systemd do at least

**Comment by nicm** [comment]
Right, but they use it for noddy stuff. Nobody seriously needs URLs in gcc or systemd. What about major programs like irssi/weechat? emacs/vim? mutt? What's the status of `less -R` support? What major terminals support it apart from VTE and iTerm2?

Anyway the patch is not finished, it needs:

- It needs changes to support the `id` parameter (not sure how this will look, can we ignore it?).

- Existing links need to be reused instead of added (fairly easy).

- It will need to be added as a terminal feature in tty-features.c.

- I don't like that it keeps adding links forever. Old ones need to be freed. I am not sure whether it is better to make the list of links per-pane instead of global, or to collect them somehow from the global list.

**Comment by dustymabe** [comment]
> Right, but they use it for noddy stuff. Nobody seriously needs URLs in gcc or systemd. What about major programs like irssi/weechat? emacs/vim? mutt? What's the status of `less -R` support? What major terminals support it apart from VTE and iTerm2?

It's a simple use but I use this all the time with `alias ls='ls --color=auto --hyperlink=auto'` in my `.bashrc` and running `ls` inside GNOME Terminal. Everything I `ls` now (PDFs, Pictures, Documents, etc) is just a right-click+open hyperlink away from being opened. I explicitly have to leave tmux now and open a new gnome-terminal window if I want the feature.

It might not be a compelling enough anecdote, but it's one datapoint.  I do appreciate you considering it even though it is more "fringe" at this point.

**Comment by sencer** [comment]
@glensc, which part you didn't understand exactly? I modified README after nicm said he is not interested in merging this PR. So I am not interested in merging it anymore. So no I am not removing it - and where the patch came from is written in that part, if you are interested prepare a PR yourself.

**Comment by kevr** [comment]
> > Right, but they use it for noddy stuff. Nobody seriously needs URLs in gcc or systemd. What about major programs like irssi/weechat? emacs/vim? mutt? What's the status of `less -R` support? What major terminals support it apart from VTE and iTerm2?
> 
> It's a simple use but I use this all the time with `alias ls='ls --color=auto --hyperlink=auto'` in my `.bashrc` and running `ls` inside GNOME Terminal. Everything I `ls` now (PDFs, Pictures, Documents, etc) is just a right-click+open hyperlink away from being opened. I explicitly have to leave tmux now and open a new gnome-terminal window if I want the feature.

> It might not be a compelling enough anecdote, but it's one datapoint. I do appreciate you considering it even though it is more "fringe" at this point.

It's definitely a useful feature. Seeing as how every other shell program out there just tries to regex links and expects that nothing is wrapped, this makes it really false positively ridden for opening links through shell content. Example: `tmux-urlview` + Mutt.

Having a standard for links in general would be absolutely fantastic and definitely a step that Linux needs to make sooner or later.

**Comment by stuaxo** [comment]
Having programming tools is a perfect use for it.

I want to click the file in the stack trace and go straight to the file in my IDE.

**Comment by lilydjwg** [comment]
I have made [a wrapper for ripgrep](https://github.com/lilydjwg/search-and-view) that displays matches with hyperlinks that will bring to the exact place the match is found. It works well with this patch.

**Comment by thornycrackers** [comment]
Kitty supports this https://sw.kovidgoyal.net/kitty/kittens/remote_file.html  and the project has 10.7k stars so i'd say it would be handy to have this feature.

**Pull request closed without merging**
