### PR TITLE
For 1872

### PR DESCRIPTION
**Pull request by gobenji**
As suggested in https://github.com/tmux/tmux/issues/1872#issuecomment-521564818

### CODE REVIEW

**Comment by nicm** [comment]
This looks great, but we can't use qsort_r because it isn't supported on OpenBSD. I'll see if I can get it added, give me a few days. If not we will need to use a temporary global instead.

Here is an updated diff with some minor style fixes and one bug fix (missing breaks inwindow_tree_cmp_session -  the WINDOW_TREE_BY_TIME case would always fall through): [tmux-1875.diff.txt](https://github.com/tmux/tmux/files/3508903/tmux-1875.diff.txt)

**Comment by nicm** [comment]
Actually that's an old version of the diff, try this [tmux-1875-2.diff.txt](https://github.com/tmux/tmux/files/3508925/tmux-1875-2.diff.txt)

**Comment by nicm** [comment]
Well, NetBSD don't have qsort_r either and FreeBSD have substantially changed their qsort code so it is not easy to copy (as well as using a different argument order). Since OpenBSD's qsort calls heapsort it would be a fairly big change to add qsort_r from scratch and I don't have time to do it now. It looks like Solaris doesn't have it as well.

I think it would be best just to use a global for the moment.

**Comment by nicm** [comment]
Here is a version which does this: [tmux-1875-3.diff.txt](https://github.com/tmux/tmux/files/3508978/tmux-1875-3.diff.txt)

**Comment by gobenji** [comment]
> Here is an updated diff with some minor style fixes and one bug fix (missing breaks inwindow_tree_cmp_session - the WINDOW_TREE_BY_TIME case would always fall through): [tmux-1875.diff.txt](https://github.com/tmux/tmux/files/3508903/tmux-1875.diff.txt)

Thanks for the review and style fixes. Good catch on the missing breaks.
Thanks also for the qsort_r() investigation.

My only further comment is regarding:

--- a/window-buffer.c
+++ b/window-buffer.c
@@ -74,6 +74,7 @@ static const char *window_buffer_sort_list[] = {
 	"name",
 	"size"
 };
+static struct mode_tree_sort_criteria window_buffer_sort;
 
Why not have it be a pointer and avoid the memcpy? Same for the other similar
instances.

**Comment by nicm** [comment]
Yes you're right they could just be pointers.

**Comment by gobenji** [comment]
Do you want me to update the pull request or do you want to work from what you've got?

**Comment by nicm** [comment]
It's OK thanks, I'll change it before I commit it.

**Comment by nicm** [comment]
This is in now, thanks!

**Pull request closed without merging**
