### PR TITLE
Add additional window-status-*-format options

### PR DESCRIPTION
**Pull request by jeroenseegers**
Options added for custom formatting of window-status-activity,
window-status-bell and window-status-last.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Possibly; not sure how useful this is, given that when we get hook supported, this can be done via that.

**Comment by jeroenseegers** [comment]
How would this work via hook support? I could only find [this discussion](http://comments.gmane.org/gmane.comp.terminal-emulators.tmux.user/3462) on it and to me it's not very clear on how this would work through a hook.

When is support for hooks expected to drop?

**Comment by nicm** [comment]
You should be able to do this already with #{?window_bell_flag,foo,bar}, I don't think we need extra options.

**Comment by jeroenseegers** [comment]
With `#{?window_bell_flag,foo,bar}` you can only change a single property as far as I understand. Using these new options you could do something along the lines of
```shell
set-window-option -g window-status-last-format '#[bg=colour10]#[fg=colour0]>#[bg=colour10]#[fg=white] #I: #W#F #[default]#[fg=colour10]>#[default]'
```
which would look something like this
screen shot 2015-07-09 at 08 27 20

It allows for greater customisation of your native tmux installation without the bloat of something like powerline.

**Comment by nicm** [comment]
New options may make this easier, but it is possible to do this without using #{?} so I don't think they are necessary.

**Comment by jeroenseegers** [comment]
Could you provide an example on how to do the above with a `#{?}` command?

**Comment by nicm** [comment]
Try something like:

set -g window-status-format '#{?window_bell_flag,#[bg=red]foo,#{?window_activity_flag,#[bg=yellow]bar,#[bg=blue]xyz}}'

**Comment by jeroenseegers** [comment]
That seems to work indeed, the syntax for it seems to be a bit fuzzy though, but thanks!

Any reason in particular why `window-status-format` and `window-status-current-format` were included, but the ones in this PR weren't? Seems to be a lot easier and consistent to have these included too.

**Comment by nicm** [comment]
They were added before we already had 80 other options and before we had #{?}.

**Pull request closed without merging**
